[OSPP][PIR] support dropout and squeeze
PaddlePaddle/Paddle2ONNX pull request #1406
Opened 2024-10-14 07:59 UTC by qzylalala

We support dropout and squeeze operation, and we can export models in `paddle.vision.models` :
* resnet50
* mobilenet_v2
* shufflenet_v2
* densenet121
* inception_v3
* squeezenet

2024-10-14 11:20 UTC, 0x3878f commented on paddle2onnx/parser/pir_parser.cc
删掉这些打印信息吧

2024-10-14 11:22 UTC, 0x3878f commented on paddle2onnx/parser/pir_parser.cc
删掉这些打印信息吧

2024-10-14 11:26 UTC, 0x3878f requested changes
LGTM

2024-10-14 11:28 UTC, 0x3878f requested changes
LGTM

2024-10-14 11:29 UTC, risemeup1 commented on paddle2onnx/parser/pir_parser.cc
> +      P2OLogger() << "  Arg name : " << name << std::endl;
这些不必要的调试信息尽量删除掉

2024-10-14 11:53 UTC, qzylalala commented on paddle2onnx/parser/pir_parser.cc
> +      P2OLogger() << "  Arg name : " << name << std::endl;
Done

2024-10-15 06:13 UTC, 0x3878f reviewed
LGTM

2024-10-15 07:46 UTC, merged