Change LoDTensorDesc to DenseTensorDesc
PaddlePaddle/Paddle2ONNX pull request #1446
Opened 2024-11-28 03:18 UTC by co63oc

Change LoDTensorDesc to DenseTensorDesc

https://github.com/PaddlePaddle/Paddle/issues/69305

2024-12-03 01:18 UTC, wanghuancoder approved these changes
LGTM

2024-12-04 09:25 UTC, Zheng-Bicheng commented
CI 为什么全挂了呢？

2024-12-04 09:27 UTC, Zheng-Bicheng commented
这个地方好像调用到了 lod_tensor 函数，新版本是删除了吗？

* https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/paddle2onnx/parser/parser.cc#L488

2024-12-04 09:28 UTC, Zheng-Bicheng commented
如果适配的是 PaddlePaddle3.0 是不是应该把 CI 脚本里面这个地方修改成 PaddlePaddle3.0

* https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/tests/run.sh#L71

2024-12-04 09:31 UTC, Zheng-Bicheng requested changes
大佬，修改后编译不通过，看下上面的修改意见，本地编译验证下呢？

2024-12-04 09:32 UTC, Zheng-Bicheng commented
编译文档

* https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/compile_local.md

2024-12-04 09:32 UTC, Zheng-Bicheng commented
@co63oc

2024-12-04 09:47 UTC, co63oc commented
> @co63oc

好的我改下

2024-12-04 10:36 UTC, co63oc commented
@Zheng-Bicheng 修改lod_tensor CI可以了，问题应该不大
![image](https://github.com/user-attachments/assets/0f4fb570-0962-443e-ba1a-cf810a4b44e5)

2024-12-05 00:04 UTC, co63oc commented
build (3.8, x64) CI状态没有变化不知道是什么问题

2024-12-05 01:40 UTC, Zheng-Bicheng approved these changes
LGTM

2024-12-05 01:40 UTC, merged

2024-12-05 01:42 UTC, Zheng-Bicheng commented
感谢大佬的贡献

```
 ________
< 牛逼 >
 --------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```