【PaddlePaddle Hackathon】在Paddle2ONNX 新增10个 Paddle 2.0 API 支持
PaddlePaddle/Paddle2ONNX pull request #357
Opened 2021-09-27 14:48 UTC by AndPuQing

**PR types** ：New features

**Describe：**

Task:  #346

在Paddle2ONNX 新增10个 Paddle 2.0 API 支持

10个API具体为：
- paddle.acos(x, name=None)
- paddle.argmin(x, axis=None, keepdim=False, dtype='int64', name=None)
- paddle.asin(x, name=None)
- paddle.atan(x, name=None)
- paddle.ceil(x, name=None)
- paddle.cos(x, name=None)
- paddle.cosh(x, name=None)
- paddle.nn.ELU(alpha=1.0, name=None)
- paddle.nn.Hardshrink(threshold=0.5, name=None)
- paddle.isfinite(x, name=None)

2021-09-28 14:49 UTC, AndPuQing commented
PR types ：New features

Task: #345 

在Paddle2ONNX 新增11个 Paddle 2.0 API 支持

2021-09-30 06:11 UTC, yeliang2258 commented on tests/test_argmin.py
> +        x = paddle.argmin(inputs, axis=0)
这种有比较多的attri的api，建议单侧中也加一个测试。

2021-09-30 07:46 UTC, AndPuQing commented on tests/test_argmin.py
> +        x = paddle.argmin(inputs, axis=0)
> 这种有比较多的attri的api，建议单侧中增加测试。

你好，已修改argmin实现方式，并增加单测

2021-10-04 08:54 UTC, jiangjiajun requested changes

2021-10-04 08:54 UTC, jiangjiajun commented on paddle2onnx/op_mapper/logic.py
> +    def opset_1(cls, graph, node, **kw):
这里面用到了3个ONNX的OP，而其中由于`IsInf`是到opset 10中才出现，因此要转换成功这个OP，至少要求opset version高于或等于10才行，因此这里函数命名也得采用`opset_10`，其它OP转换亦同理

2021-10-04 09:35 UTC, AndPuQing commented on paddle2onnx/op_mapper/logic.py
> +    def opset_1(cls, graph, node, **kw):
Thank you for your review, I will make changes in the next submission.

2021-10-05 01:30 UTC, yeliang2258 approved these changes

2021-10-05 06:28 UTC, jiangjiajun approved these changes
Thanks for your contribution! This pull request looks good to me.

2021-10-05 13:04 UTC, AndPuQing commented
> Thanks for your contribution! This pull request looks good to me.

Thank you for your review. Should I send an email to request a merge?

2021-10-05 16:51 UTC, merged