【PaddlePaddle Hackathon】在Paddle2ONNX 新增11个 Paddle 2.0 API 支持
PaddlePaddle/Paddle2ONNX pull request #358
Opened 2021-09-29 04:25 UTC by AndPuQing

PR types ：New features

Describe：

Task: #345

在Paddle2ONNX 新增11个 Paddle 2.0 API 支持

11个 API 具体为：

- paddle.erf(x, name=None)

- paddle.floor_mod(x, y, name=None)

- paddle.floor(x, name=None)

- paddle.isinf(x, name=None)

- paddle.has_nan(x)

- paddle.isnan(x, name=None)

- paddle.less_than(x, y, name=None)

- paddle.log2(x, name=None)

- paddle.logical_not(x, out=None, name=None)

- paddle.logical_or(x, y, out=None, name=None)

- paddle.logsumexp(x, axis=None, keepdim=False, name=None)

2021-10-08 02:50 UTC, yeliang2258 commented on paddle2onnx/op_mapper/logic.py
> +    support_opset_verision_range = (6, 12)
onnx的版本有误

2021-10-08 02:50 UTC, yeliang2258 commented on paddle2onnx/op_mapper/logic.py
> +    support_opset_verision_range = (7, 12)
or在onnx中有两个版本，请对应都实现。

2021-10-08 02:50 UTC, yeliang2258 commented on paddle2onnx/op_mapper/math.py
> +class IsInf():
类名有误

2021-10-08 02:50 UTC, yeliang2258 commented on paddle2onnx/op_mapper/math.py
> +    support_opset_verision_range = (7, 12)
less在onnx中有多个版本，请一并实现

2021-10-08 08:07 UTC, jiangjiajun requested changes

2021-10-08 08:07 UTC, jiangjiajun commented on paddle2onnx/op_mapper/logic.py
> +    support_opset_verision_range = (6, 12)
单词中所有的`version`都写错成了`verision`

注意到你先前的这个PR https://github.com/PaddlePaddle/Paddle2ONNX/pull/357 中也有同样的问题，请单独提一个PR解决上个PR的遗留错误

2021-10-08 08:07 UTC, jiangjiajun commented on paddle2onnx/op_mapper/math.py
> +class IsInf_v2():
这种带版本号的，在写class时，命名不需要加入版本号，在class中再处理不同版本的OP

2021-10-08 08:07 UTC, jiangjiajun commented on paddle2onnx/op_mapper/math.py
> +class IsNaN_v2():
命名规则同上

2021-10-08 11:38 UTC, AndPuQing commented on paddle2onnx/op_mapper/logic.py
> +    support_opset_verision_range = (7, 12)
> or在onnx中有两个版本，请对应都实现。

你好，在测试版本1到6的过程中发生如下报错：

```shell
 Error in Node:Cast_0 : Mismatched attribute type in 'Cast_0 : to'
```

为确定是否是特定算子问题，测试了shape算子、cast算子，均发生如上错误，现在判断为Cast算子的问题，暂时无法解决该问题

2021-10-08 12:27 UTC, yeliang2258 commented on paddle2onnx/op_mapper/logic.py
> +    support_opset_verision_range = (7, 12)
你好，请问你的实现方式是？or-1中的broadcast是否需要特殊设置呢？
![image](https://user-images.githubusercontent.com/30516196/136556556-08452d05-6dc2-46ba-844b-4611aaf93147.png)

2021-10-08 12:35 UTC, AndPuQing commented on paddle2onnx/op_mapper/logic.py
> +    support_opset_verision_range = (7, 12)
你好，现在写法如下
```python
@op_mapper('logical_or')
class LogicalOr():
    support_opset_version_range = (1, 12)

    @classmethod
    def opset_1(cls, graph, node, **kw):
        graph.make_node('Or',
                        inputs=[node.input('X', 0),
                                node.input('Y', 0)],
                        broadcast=1,
                        outputs=node.output('Out'))

    @classmethod
    def opset_6(cls, graph, node, **kw):
        graph.make_node('Or',
                        inputs=[node.input('X', 0),
                                node.input('Y', 0)],
                        outputs=node.output('Out'))
```
加上broadcast依然报出如上错误

2021-10-08 12:45 UTC, yeliang2258 commented on paddle2onnx/op_mapper/logic.py
> +    support_opset_verision_range = (7, 12)
看了一下，好像opset version版本太低的也没有必要再去支持了，那就按照之前那个写法吧。写7到12。

2021-10-08 12:46 UTC, yeliang2258 commented on paddle2onnx/op_mapper/logic.py
> +    support_opset_verision_range = (7, 12)
如果你有版本问题拿不准的，可以参考：
https://github.com/onnx/onnx/blob/master/docs/Operators.md

2021-10-08 12:47 UTC, yeliang2258 commented on paddle2onnx/op_mapper/logic.py
> +    support_opset_verision_range = (7, 12)
onnxruntime和opset version也是有一个对应关系的，具体可以看：https://github.com/microsoft/onnxruntime/blob/master/docs/Versioning.md

2021-10-08 12:58 UTC, AndPuQing commented on paddle2onnx/op_mapper/logic.py
> +    support_opset_verision_range = (7, 12)
好，之后将修改版本，thank you review!

2021-10-08 13:59 UTC, AndPuQing commented on paddle2onnx/op_mapper/math.py
> +    support_opset_verision_range = (7, 12)
当我尝试时，返回
```shell
NOT_IMPLEMENTED : Could not find an implementation for Less(1) node with name 'Less_0'
```

2021-10-09 02:12 UTC, yeliang2258 approved these changes

2021-10-09 08:38 UTC, yeliang2258 commented
你好，op_list也一起更新一下，之前已经merge的两个PR也再另提一个更新op_list的PR。

2021-10-09 09:41 UTC, AndPuQing commented
> 你好，op_list也一起更新一下，之前已经merge的两个PR也再另提一个更新op_list的PR。谢谢

已更新

2021-10-11 06:13 UTC, yeliang2258 approved these changes

2021-10-11 06:22 UTC, jiangjiajun requested changes

2021-10-11 06:22 UTC, jiangjiajun commented on paddle2onnx/op_mapper/math.py
> +        graph.make_node('Div', inputs=[lnx, ln2], outputs=node.output('Out'))
建议将ln2提前计算好，作为一个constant，可以降低转换后模型的计算量， log10同理

可以参考下pytorch的转换方式 https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic_opset9.py#L1569

2021-10-11 09:10 UTC, AndPuQing commented on paddle2onnx/op_mapper/math.py
> +        graph.make_node('Div', inputs=[lnx, ln2], outputs=node.output('Out'))
Good suggestion, It has been modified.

2021-10-12 02:13 UTC, jiangjiajun requested changes

2021-10-12 02:13 UTC, jiangjiajun commented on tests/test_erf.py
> +    simplr Net
Simple Net?

2021-10-12 02:13 UTC, jiangjiajun commented on tests/test_erf.py
> +    simplr Net
这个单词在其它单测也有，也麻烦检查下此前已合入的PR，如若有类似问题，麻烦另提一个PR修复拼写问题

2021-10-12 02:31 UTC, jiangjiajun commented on tests/test_erf.py
> +    simplr Net
刚发现这个单词错误在最早前的单测就存在， @Zeref996 会提一个PR来统一修复其它单测中的拼写错误

@AndPuQing 修复目前还未合入的两个PR中的此拼写错误即可，已合入的无需再处理

2021-10-12 05:09 UTC, AndPuQing commented on tests/test_erf.py
> +    simplr Net
已处理

2021-10-12 06:15 UTC, jiangjiajun approved these changes
LGTM

2021-10-13 02:22 UTC, merged