【PaddlePaddle Hackathon】在Paddle2ONNX 新增11个 Paddle 2.0 API 支持
PaddlePaddle/Paddle2ONNX pull request #362
Opened 2021-10-03 09:30 UTC by AndPuQing

**PR types** ：New features

**Describe：**

Task:  #344

在Paddle2ONNX 新增11个 Paddle 2.0 API 支持

10个API具体为：
- paddle.log10(x, name=None)
- paddle.log1p(x, name=None)
- paddle.logical_xor(x, y, out=None, name=None)
- paddle.nn.LogSigmoid(name=None)
- paddle.all(x, axis=None, keepdim=False, name=None)
- paddle.any(x, axis=None, keepdim=False, name=None)
- paddle.round(x, name=None)
- paddle.rsqrt(x, name=None)
- paddle.nn.functional.selu(x, scale=1.0507, alpha=1.67326, name=None)
- paddle.sign(x, name=None)
- paddle.sin(x, name=None)

2021-10-08 03:19 UTC, yeliang2258 commented on paddle2onnx/op_mapper/activation.py
> +    support_opset_verision_range = (6, 12)
和下面的opset_1不匹配

2021-10-08 03:19 UTC, yeliang2258 commented on paddle2onnx/op_mapper/logic.py
> +    def opset_6(cls, graph, node, **kw):
需要和上面的support_opset_verision_range对应，请改为opset_7

2021-10-08 03:19 UTC, yeliang2258 commented on paddle2onnx/op_mapper/math.py
> +    def opset_1(cls, graph, node, **kw):
请改为opset_7

2021-10-08 03:19 UTC, yeliang2258 commented on paddle2onnx/op_mapper/math.py
> +    support_opset_verision_range = (7, 12)
版本有误

2021-10-08 03:19 UTC, yeliang2258 commented on paddle2onnx/op_mapper/math.py
> +    support_opset_verision_range = (7, 12)
版本有误

2021-10-08 03:19 UTC, yeliang2258 commented on paddle2onnx/op_mapper/math.py
> +    def opset_1(cls, graph, node, **kw):
请和上面定的版本匹配

2021-10-08 03:19 UTC, yeliang2258 commented on paddle2onnx/op_mapper/math.py
> +    def opset_1(cls, graph, node, **kw):
请和上方support_opset_verision_range匹配

2021-10-08 03:19 UTC, yeliang2258 commented on paddle2onnx/op_mapper/math.py
> +    def opset_1(cls, graph, node, **kw):
请和上方support_opset_verision_range匹配

2021-10-08 03:19 UTC, yeliang2258 commented on paddle2onnx/op_mapper/math.py
> +    def opset_1(cls, graph, node, **kw):
请和上方support_opset_verision_range匹配

2021-10-08 08:10 UTC, jiangjiajun requested changes

2021-10-08 08:10 UTC, jiangjiajun commented on paddle2onnx/op_mapper/activation.py
> +    support_opset_verision_range = (6, 12)
这个PR也同样存在`version`拼写问题

2021-10-08 14:04 UTC, AndPuQing commented on paddle2onnx/op_mapper/math.py
> +    support_opset_verision_range = (7, 12)
尝试更低版本时，返回

```shell
NOT_IMPLEMENTED : Could not find an implementation for Add(1) node with name 'Add_0'
```

2021-10-08 14:05 UTC, yeliang2258 commented
直接实现7以上的版本吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月8日(周五) 晚上10:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/Paddle2ONNX] 【PaddlePaddle Hackathon】在Paddle2ONNX 新增11个 Paddle 2.0 API 支持 (#362)




 
@AndPuQing commented on this pull request.
 
 
In paddle2onnx/op_mapper/math.py:
 &gt; + +    @classmethod +    def opset_1(cls, graph, node, **kw): +        ten = graph.make_node( +            'Constant', attrs={ +                'dtype': dtypes.ONNX.FLOAT, +                'value': [10] +            }) +        ln2 = graph.make_node('Log', inputs=[ten]) +        lnx = graph.make_node('Log', inputs=node.input('X')) +        graph.make_node('Div', inputs=[lnx, ln2], outputs=node.output('Out')) + + ***@***.***_mapper('log1p') +class Log1p(): +    support_opset_verision_range = (7, 12)  
尝试更低版本时，返回
 NOT_IMPLEMENTED : Could not find an implementation for Add(1) node with name 'Add_0'
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-10-08 14:14 UTC, AndPuQing commented
> 直接实现7以上的版本吧
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年10月8日(周五) 晚上10:04 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [PaddlePaddle/Paddle2ONNX] 【PaddlePaddle Hackathon】在Paddle2ONNX 新增11个 Paddle 2.0 API 支持 (#362) @AndPuQing commented on this pull request. In paddle2onnx/op_mapper/math.py: &gt; + + @classmethod + def opset_1(cls, graph, node, **kw): + ten = graph.make_node( + 'Constant', attrs={ + 'dtype': dtypes.ONNX.FLOAT, + 'value': [10] + }) + ln2 = graph.make_node('Log', inputs=[ten]) + lnx = graph.make_node('Log', inputs=node.input('X')) + graph.make_node('Div', inputs=[lnx, ln2], outputs=node.output('Out')) + + ***@***.***_mapper('log1p') +class Log1p(): + support_opset_verision_range = (7, 12) 尝试更低版本时，返回 NOT_IMPLEMENTED : Could not find an implementation for Add(1) node with name 'Add_0' — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.


好

2021-10-09 02:28 UTC, yeliang2258 requested changes

2021-10-09 02:28 UTC, yeliang2258 commented on paddle2onnx/op_mapper/math.py
> +    def opset_1(cls, graph, node, **kw):
![image](https://user-images.githubusercontent.com/30516196/136640668-5eb55898-ca8f-447e-8bd6-a6fb14c659b8.png)
请参照这个哦

2021-10-09 02:58 UTC, AndPuQing commented on paddle2onnx/op_mapper/math.py
> +    def opset_1(cls, graph, node, **kw):
已修改

2021-10-09 06:03 UTC, yeliang2258 approved these changes

2021-10-09 06:19 UTC, jiangjiajun approved these changes

2021-10-09 06:20 UTC, jiangjiajun commented
Thanks for your contribution!

2021-10-09 06:20 UTC, merged