【PaddlePaddle Hackathon】在Paddle2ONNX 新增11个 Paddle 2.0 API 支持
PaddlePaddle/Paddle2ONNX pull request #363
Opened 2021-10-03 16:24 UTC by AndPuQing

PR types ：New features

Describe：

Task: #343

在Paddle2ONNX 新增11个 Paddle 2.0 API 支持

11个 API 具体为：

- paddle.argsort(x, axis=- 1, descending=False, name=None)
- paddle.nn.functional.hardtanh(x, min=-1.0, max=1.0, name=None)
- paddle.dist(x, y, p=2)
- paddle.dot(x, y, name=None)
- paddle.index_select(x, index, axis=0, name=None)
- paddle.nn.functional.log_softmax(x, axis=- 1, dtype=None, name=None)
- paddle.mv(x, vec, name=None)
- paddle.nn.Pad1D(padding, mode='constant', value=0.0, data_format='NCL', name=None)
- paddle.sinh(x, name=None)
- paddle.numel(x)
- paddle.nn.functional.softsign(x, name=None)

2021-10-08 03:41 UTC, yeliang2258 commented on paddle2onnx/op_mapper/nn.py
> +    def opset_1(cls, graph, node, **kw):
opset version 1不支持该操作

2021-10-08 03:41 UTC, yeliang2258 commented on paddle2onnx/op_mapper/nn.py
> +    support_opset_verision_range = (6, 12)
版本不对

2021-10-08 03:41 UTC, yeliang2258 commented on paddle2onnx/op_mapper/search.py
> +    support_opset_verision_range = (11, 12)
使用到的topk，gather和constant几个op在低版本的opset version中也是支持的，请将低版本的也一并实现。

2021-10-09 04:15 UTC, AndPuQing commented on paddle2onnx/op_mapper/search.py
> +    support_opset_verision_range = (11, 12)
topk低版本中没有顺序输出。所以当descending=False时raise error。有尝试使用slice倒序，但是slice倒序索引直到opset_version=11才支持。

2021-10-09 10:56 UTC, yeliang2258 commented on paddle2onnx/op_mapper/search.py
> +    support_opset_verision_range = (11, 12)
那低版本就先实现descending=True的情况，如果检测到低版本使用了无法实现的descending=False，给出一个warning提示用户重新选择opset version

2021-10-09 10:57 UTC, yeliang2258 commented
另外解决一下merge冲突，更新一下op_list

2021-10-10 16:56 UTC, AndPuQing commented on paddle2onnx/op_mapper/search.py
> +    support_opset_verision_range = (11, 12)
已支持

2021-10-12 06:41 UTC, jiangjiajun requested changes

2021-10-12 06:41 UTC, jiangjiajun commented on paddle2onnx/op_mapper/math.py
> +@op_mapper('size')
`size`应该归类为`tensor`下，此OP实现放在tensor.py中

但是目前Paddle2ONNX确实存在OP分类规则不严谨的地方， @yeliang2258 后面我们可以考虑把所有OP重新梳理下，分类做到与飞桨框架一致

2021-10-12 06:41 UTC, jiangjiajun commented on paddle2onnx/op_mapper/math.py
> +        for i in range(input_shape[0]):
此实现在`input_shape`为动态情况下（如[-1, 8]），将会导致意外的错误。

可以考虑采用普通的`elementwise_mul` + `reduce_sum`来实现batch dot

2021-10-12 09:14 UTC, AndPuQing commented on paddle2onnx/op_mapper/math.py
> +        for i in range(input_shape[0]):
修改了实现方式，但是因为Mul opset 支持到7，所以版本需要7及以上

2021-10-12 09:15 UTC, AndPuQing commented on paddle2onnx/op_mapper/math.py
> +@op_mapper('size')
已移动位置

2021-10-12 12:42 UTC, jiangjiajun requested changes

2021-10-12 12:42 UTC, jiangjiajun commented on paddle2onnx/op_mapper/math.py
> +    def opset_7(cls, graph, node, **kw):
此处Reduce Sum的axis指定为1，在dot的输入都为1D Tensor时, 会出错

2021-10-12 12:42 UTC, jiangjiajun commented on tests/test_dot.py
> +        paddle.to_tensor(randtool("float", 0, 1, [3, 10]).astype('float32')))
paddle的dot与torch或其它框架存在差异
torch.dot仅支持1D Tensor；
paddle.dot支持1D Tensor，其行为与torch.dot一致；同时支持2D Tensor，当为2D Tensor时，其行为即为`batch dot`

2021-10-12 14:27 UTC, AndPuQing commented on paddle2onnx/op_mapper/math.py
> +    def opset_7(cls, graph, node, **kw):
抱歉，确实疏忽了，已修改为`len(node.input_shape('X', 0)) - 1`作为`axes`

2021-10-12 14:28 UTC, AndPuQing commented on tests/test_dot.py
> +        paddle.to_tensor(randtool("float", 0, 1, [3, 10]).astype('float32')))
加入对1D tensor情况的单测

2021-10-13 02:37 UTC, jiangjiajun requested changes

2021-10-13 02:37 UTC, jiangjiajun commented on tests/test_nn_Pad1D.py
> +        self._pad = paddle.nn.Pad1D(padding=1, mode=self.mode)
这里组网仅测试了padding为常数值的情况，需包含以下几种情况
1. padding=1
2. padding=[1, 2]
3. padding=Tensor([1])
4. padding=Tensor([1, 2])

2021-10-13 02:38 UTC, jiangjiajun commented
注意到当前代码已经出现了冲突 @AndPuQing

2021-10-13 13:02 UTC, AndPuQing commented on tests/test_nn_Pad1D.py
> +        self._pad = paddle.nn.Pad1D(padding=1, mode=self.mode)
tensor输入的支持似乎是一个遗留问题，见如下`TODO`

https://github.com/PaddlePaddle/Paddle2ONNX/blob/9606019edb081bdd4739ce6dd8f43f4d8a8050f2/paddle2onnx/op_mapper/tensor.py#L863

在转换中发现，是paddle源码中判断当`pad`是`Variable`时，将`pad`放入`inputs`中，如下代码

https://github.com/PaddlePaddle/Paddle/blob/06d47ff7e2dff1d2daa96eaff525d81ef7c013eb/python/paddle/nn/functional/common.py#L1325

这样在转换成onnx后需要网络输入padding，但是这个pad在paddle中是由attr输入的，使得onnx网络不能拿到该节点。但若写成输入padding形式，如下

```python
obj.set_input_data(
    "input_data",
    paddle.to_tensor(
        randtool("float", -1, 1, [3, 1, 10]).astype('float32')),
    paddle.to_tensor([1, 2]).astype('int32'))
```

在paddle这边会遇到动转静类型问题

```python
>   ???
E   TypeError: In transformed code:
E
E       File "/home/ray/workspace/PuQing/Paddle2ONNX/tests/test_nn_Pad1D.py", line 38, in forward
E           print(padding)
E           self._pad = paddle.nn.Pad1D(padding=padding, mode=self.mode)
E           x = self._pad(inputs)
E           ~~~~~~~~~~~~~~~~~~~~~ <--- HERE
E           return x
E
E       TypeError: _set_attr(): incompatible function arguments. The following argument types are supported:
E       1. (self: paddle.fluid.core_avx.OpDesc, arg0: str, arg1: Variant) -> None
E
E   Invoked with: <paddle.fluid.core_avx.OpDesc object at 0x7fb2b3f12d30>, 'paddings', [0, 0, 0, 0, var 1 : LOD_TENSOR.shape(2,).dtype(int32).stop_gradient(False), var 1 : LOD_TENSOR.shape(2,).dtype(int32).stop_gradient(False)]
```

2021-10-17 08:42 UTC, jiangjiajun commented
@AndPuQing CI中有部分单测没过，可点进去（login as guest）看下build_log，在里面可以找到具体出错的原因

2021-10-17 11:15 UTC, AndPuQing commented
> @AndPuQing CI中有部分单测没过，可点进去（login as guest）看下build_log，在里面可以找到具体出错的原因

提示访问错误，正在请交流群群主看看，周一回复

2021-10-19 12:50 UTC, yeliang2258 commented on tests/test_nn_Pad1D.py
> +        self._pad = paddle.nn.Pad1D(padding=1, mode=self.mode)
![image](https://user-images.githubusercontent.com/30516196/137912565-02a53d09-12fd-4209-9bbd-cf1a41db1853.png)
尝试这样写单测？你在看看能否改改pad的OP转换，将其转成功

2021-10-19 15:31 UTC, AndPuQing commented on tests/test_nn_Pad1D.py
> +        self._pad = paddle.nn.Pad1D(padding=1, mode=self.mode)
emm，就像这样写吗？
```python
def test_Pad1D_paddingTensor():
    """
    api: paddle.nn.Pad1D
    op version: 12
    """
    op = Net(padding=paddle.to_tensor(np.array([1, 2])).astype('int32'))
    op.eval()
    # net, name, ver_list, delta=1e-6, rtol=1e-5
    obj = APIOnnx(op, 'nn_Pad1D', [12])
    obj.set_input_data(
        "input_data",
        paddle.to_tensor(
            randtool("float", -1, 1, [3, 1, 10]).astype('float32')))
    obj.run()
```

pad代码并未改动，报错发生在
```python
        elif node.attr('data_format') == 'NCDHW':
            onnx_paddings = [
>               0, 0, paddings[4], paddings[2], paddings[0], 0, 0, paddings[5],
                paddings[3], paddings[1]
E               IndexError: list index out of range
```
打印该结点
```python
    def convert_padding(cls, node, **kw):
        x_shape = node.input_shape('X', 0)
        paddings = node.attr('paddings')
>       raise NameError(paddings)
E       NameError: []
```
若打印node_inputs
```python
    @classmethod
    def convert_padding(cls, node, **kw):
        x_shape = node.input_shape('X', 0)
        paddings = node.attr('paddings')
>       raise NameError(node.input('Paddings'))
E       NameError: ['concat_0.tmp_0']
```
就像上面说的，paddings如果是tensor将会在input中

2021-10-19 15:45 UTC, yeliang2258 commented on tests/test_nn_Pad1D.py
> +        self._pad = paddle.nn.Pad1D(padding=1, mode=self.mode)
上面单测报错应该是pad使用tensor作为输入的时候对size有要求，你按照我的那个实例的参数设置一下。你看看之前的开发例子，看能否将这个convert_padding修改符合要求。

2021-10-20 14:21 UTC, AndPuQing commented
> @AndPuQing CI中有部分单测没过，可点进去（login as guest）看下build_log，在里面可以找到具体出错的原因

CI似乎通过了

2021-10-23 09:52 UTC, AndPuQing commented
最新push版本是能支持Tensor的paddings动态输入，但是还不完善，以下是我目前知道该OP的信息

**Padddle部分的计算图**

![](https://ss.im5i.com/2021/10/23/yfpoD.png)

在进入Pad3D算子之前，Paddings会Concat一下。而在转化时，node只能拿到Concat之后的节点名称`concat_1.tmp_0`，在转化为onnx模型后，如下图：

![](https://ss.im5i.com/2021/10/23/yf7Oj.png)

网络需要一个命名为`auto_25_`的输入，但是矛盾的是该输入是在Concat节点中输入的，所以我添加了一个名为`auto_25_`的节点输入，如下

```python
# tensor.py
graph.add_input_node('auto_25_', [2],
                                 dtypes.DTYPE_ONNX_STR_MAP['float64'])
```

这样修改后，在onnx推理阶段就不能使用`onnxbase.py`中的API进行推理了，只能自定义输入名，如下

```python
# test_nn_Pad1D.py
sess = InferenceSession(
        os.path.join(os.getcwd(), 'nn_Pad1D', 'nn_Pad1D' + '12' + '.onnx'))
x = np.random.random([3, 1, 10]).astype('float32')
y = np.array([1, 2]).astype('int32')
ort_inputs = {sess.get_inputs()[0].name: x, sess.get_inputs()[1].name: y}
```

在本地测试中，以上写法是能达到精度的，但是问题很明显，`auto_25_`输入名是不定的，所以我修改了输入进paddings的名字，并且进输入pad名固定为`pad`，如下

```python
# tensor.py
graph.add_input_node('pad', [2],dtypes.DTYPE_ONNX_STR_MAP['float64'])
```
```python
# test_nn_Pad1D.py
paddings = paddle.to_tensor([1, 2]).astype('int32')
paddings.name = 'pad'
op = Net(padding=paddings)
op.eval()
# net, name, ver_list, delta=1e-6, rtol=1e-5
obj = APIOnnx(op, 'nn_Pad1D', [12])
```

以上我的实现，希望有所用。 @yeliang2258 @jiangjiajun

2021-10-25 08:15 UTC, yeliang2258 commented on tests/test_nn_Pad1D.py
> +        self._pad = paddle.nn.Pad1D(padding=1, mode=self.mode)
确实这个padding为tensor的输入比较复杂，那暂时先不实现这个例子吧，padding为tensor输入的情况先不实现。

2021-10-26 02:31 UTC, yeliang2258 approved these changes

2021-10-26 05:36 UTC, jiangjiajun approved these changes

2021-10-26 05:37 UTC, merged