fix a bug for conv2dtranspose in padding and output_padding
PaddlePaddle/Paddle2ONNX pull request #408
Opened 2021-11-30 07:16 UTC by neonhuang

fix a bug for conv2dtranspose in padding and output_padding

2021-12-03 11:14 UTC, jiangjiajun requested changes

2021-12-03 11:14 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +            if graph.opset_version < 11:
拆成opset 11, opset 13

2021-12-03 11:32 UTC, jiangjiajun requested changes

2021-12-03 11:32 UTC, jiangjiajun commented on paddle2onnx/op_mapper/nn.py
> +                inputs=intput_x,
intput_x? 是不是打错了

2021-12-03 11:32 UTC, jiangjiajun commented on tests/test_nn_Conv2DTranspose.py
> +
添加groups， output_paddings测试

2021-12-05 02:52 UTC, neonhuang commented on paddle2onnx/op_mapper/tensor.py
> +            if graph.opset_version < 11:
done

2021-12-05 02:57 UTC, neonhuang commented on paddle2onnx/op_mapper/nn.py
> +                inputs=intput_x,
没有打错，只是把输入提取出来而已，上面会用到

2021-12-06 03:45 UTC, neonhuang commented on tests/test_nn_Conv2DTranspose.py
> +
done

2021-12-09 12:35 UTC, jiangjiajun requested changes

2021-12-09 12:35 UTC, jiangjiajun commented on paddle2onnx/op_mapper/nn.py
> +                inputs=intput_x,
改成input_x，intput_x外人一看就是拼错的写法

2021-12-09 12:35 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +            axes = axes_new
在PR的description中详细描述清楚具体的错误情况，便于Review时了解为什么需要这样来修改代码

2021-12-09 12:35 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +        axes_new = [axe + ndim for axe in axes if axe < 0]
axes的单数是axis

2021-12-09 12:35 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +        if len(axes_new) > 0:
为什么要加这个判断

2021-12-09 12:35 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +                axes = axes_new
同上

2021-12-09 12:35 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +                    axis_data = param.attribute[0].t.int64_data
这什么不能直接从graph.parameters里面取，而是要遍历graph.parameters，然后来作对比，我注意到此前的代码也是这样的逻辑，确认下是否可以简化

2021-12-09 12:35 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +                    axis_data = param.attribute[0].t.int64_data
同上

2021-12-09 12:35 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +                       'value': axis_data})
另外既然在opset13中已经支持Tensor形式的axis，那就不需要再用上面graph.parameters的形式，先前tensor取得值，再从值转成const tensor了

2021-12-10 02:12 UTC, neonhuang commented on paddle2onnx/op_mapper/tensor.py
> +            axes = axes_new
这个有描述，就是（1）修复opset 1时，axes必须为非负数问题；

2021-12-10 02:12 UTC, neonhuang commented on paddle2onnx/op_mapper/tensor.py
> +        axes_new = [axe + ndim for axe in axes if axe < 0]
修复

2021-12-10 02:13 UTC, neonhuang commented on paddle2onnx/op_mapper/tensor.py
> +        if len(axes_new) > 0:
（1）修复opset 1时，axes必须为非负数问题；很明显如果axes全为非负数，那么axes_new会为空

2021-12-10 02:13 UTC, neonhuang commented on paddle2onnx/op_mapper/tensor.py
> +                axes = axes_new
（1）修复opset 1时，axes必须为非负数问题；很明显如果axes全为非负数，那么axes_new会为空

2021-12-10 02:51 UTC, jiangjiajun requested changes

2021-12-10 02:51 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +        if len(axes_new) > 0:
如果axes为[1, 3, -1, 5]， ndim为8， 那axes_new就变成了[7]?

2021-12-10 02:51 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +        if len(axes_new) > 0:
不确定上面是否是符合预期的情况，看起来可能会导致出错。

此外代码可以简写为 `axes = [(axis+ndim)%ndim for axis in axes]`

2021-12-10 09:17 UTC, neonhuang commented on paddle2onnx/op_mapper/tensor.py
> +                       'value': axis_data})
已经修复

2021-12-10 09:43 UTC, neonhuang commented on paddle2onnx/op_mapper/tensor.py
> +        if len(axes_new) > 0:
已经修复

2021-12-10 09:44 UTC, neonhuang commented on paddle2onnx/op_mapper/tensor.py
> +                    axis_data = param.attribute[0].t.int64_data
已经修复

2021-12-10 09:44 UTC, neonhuang commented on paddle2onnx/op_mapper/tensor.py
> +                    axis_data = param.attribute[0].t.int64_data
已经修复

2021-12-13 02:40 UTC, neonhuang commented on paddle2onnx/op_mapper/nn.py
> +                inputs=intput_x,
已经改过了

2021-12-13 02:41 UTC, jiangjiajun requested changes

2021-12-13 02:41 UTC, jiangjiajun commented on paddle2onnx/op_mapper/nn.py
> +            if max(k_size) <= max(pads):
else的逻辑不需要了？

2021-12-13 02:45 UTC, neonhuang commented on paddle2onnx/op_mapper/nn.py
> +            if max(k_size) <= max(pads):
需要的吧

2021-12-13 13:08 UTC, jiangjiajun requested changes

2021-12-13 13:08 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +        axes.sort()
为什么要sort，不sort会有什么问题

2021-12-13 13:08 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +        axes_node = graph.make_node(
这里为什么又不需要sort呢

2021-12-13 13:08 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +
- `sort(axes) == axes`
- `len(set(axes)) == len(axes)`

2021-12-14 02:55 UTC, neonhuang commented on paddle2onnx/op_mapper/tensor.py
> +
修复

2021-12-14 02:55 UTC, neonhuang commented on paddle2onnx/op_mapper/tensor.py
> +        axes_node = graph.make_node(
已回复

2021-12-14 02:55 UTC, neonhuang commented on paddle2onnx/op_mapper/tensor.py
> +        axes.sort()
已回复

2021-12-14 03:01 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +        axes.sort()
不sort，会在onnxruntime中报警告

2021-12-14 03:01 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +        axes_node = graph.make_node(
opset 13中不sort， onnxruntime也可以支持，无警告

2021-12-14 03:01 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +        axes_node = graph.make_node(
@neonhuang 后面PR中我们将代码中的沟通也同步在这里，线下的沟通无法让其他人在看代码修改时知道原因

2021-12-14 07:08 UTC, jiangjiajun approved these changes

2021-12-14 07:08 UTC, merged