fix upsamle and resize opset
PaddlePaddle/Paddle2ONNX pull request #418
Opened 2021-12-08 10:59 UTC by neonhuang

fix upsample and resize opset and add test case

2021-12-09 13:11 UTC, jiangjiajun requested changes

2021-12-09 13:11 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +                "Resize in onnx(opset<=10) only support coordinate_transformation_mode: " \
提示改为提示paddle op的信息，无法从coordinate_transformation_mode反推回去paddle的op限制条件是什么

2021-12-09 13:11 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +            scaleValue = [1, 1]
变量不要出现大写，改成scale_value

2021-12-13 01:51 UTC, neonhuang commented on paddle2onnx/op_mapper/tensor.py
> +            scaleValue = [1, 1]
修复

2021-12-13 02:14 UTC, neonhuang commented on paddle2onnx/op_mapper/tensor.py
> +                "Resize in onnx(opset<=10) only support coordinate_transformation_mode: " \
已经修复

2021-12-17 03:16 UTC, yeliang2258 requested changes

2021-12-17 03:16 UTC, yeliang2258 commented on paddle2onnx/op_mapper/tensor.py
> +            "The conv data layout should be 'NCHW' , but received data format " \
conv data

2022-03-01 11:11 UTC, jiangjiajun approved these changes

2022-04-12 07:19 UTC, jiangjiajun approved these changes

2022-04-12 07:19 UTC, merged