New auto scan test dev
PaddlePaddle/Paddle2ONNX pull request #423
Opened 2021-12-10 10:54 UTC by yeliang2258

1. Add test_auto_scan_lookup_table_v2.py for lookup_table_v2, add opset version 13 support and add padding_idx support.
2. Fix data_format assert in conv2d、pool2d and affine_channel.
3. Add generator_data function, users can write their own data generation function, Please refer to test_auto_scan_lookup_table_v2.py

2021-12-13 08:34 UTC, jiangjiajun requested changes

2021-12-13 08:34 UTC, jiangjiajun commented on paddle2onnx/op_mapper/math.py
> +            assert node.attrs['data_format'] == 'NCHW' or node.attrs['data_format'] == 'NCHW',  \
两个相同的判断

2021-12-13 08:34 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +                print(name)
删除

2021-12-13 08:34 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +                    weight = param['data']
这里为什么需要循环遍历dict来查找key，是否可以`if name in graph.parameters`即可解决

2021-12-13 08:34 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +                assert False, "opset version < 11 do not support padding_idx !=-1 and weight is tensor, please set opset version > 11"
直接采用TVM relay中的转换方式不就可以解决了吗

2021-12-13 08:34 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +                    weight = param['data']
同上

2021-12-13 08:34 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +                weight[padding_idx] = 0.0
在这里记上TODO，当前这种实现方式存在逻辑未考虑全的问题

理论上这个weight即可以是tensor，也可以是padding，但在是weight的情况下，当前通过修改weight来达到目的，这步原本应该放到最终生成模型后的pass去做，而目前是直接在转换过程做，如果这个weight被另外其余的OP也在使用，那会导致出错

2021-12-13 08:34 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +                weight[padding_idx] = 0.0
记上TODO

2021-12-13 08:34 UTC, jiangjiajun commented on tests/auto_scan_test.py
> +                        data = shape()
加上注释，为什么需要加这个判断，后期提升单测代码的可维护性

2021-12-13 13:38 UTC, yeliang2258 commented on paddle2onnx/op_mapper/tensor.py
> +                assert False, "opset version < 11 do not support padding_idx !=-1 and weight is tensor, please set opset version > 11"
done

2021-12-13 13:38 UTC, yeliang2258 commented on paddle2onnx/op_mapper/tensor.py
> +                    weight = param['data']
已经删除

2021-12-13 13:38 UTC, yeliang2258 commented on paddle2onnx/op_mapper/tensor.py
> +                weight[padding_idx] = 0.0
已经删除

2021-12-13 13:39 UTC, yeliang2258 commented on tests/auto_scan_test.py
> +                        data = shape()
这是由于想让开发者自己能够定义一个数据生成函数

2021-12-13 13:40 UTC, yeliang2258 commented on paddle2onnx/op_mapper/tensor.py
> +                weight[padding_idx] = 0.0
已经删除，根据TVM的paddle前端更新了代码

2021-12-13 13:40 UTC, yeliang2258 commented on paddle2onnx/op_mapper/math.py
> +            assert node.attrs['data_format'] == 'NCHW' or node.attrs['data_format'] == 'NCHW',  \
done

2021-12-13 13:40 UTC, yeliang2258 commented on paddle2onnx/op_mapper/tensor.py
> +                print(name)
done

2021-12-13 13:40 UTC, yeliang2258 commented on paddle2onnx/op_mapper/tensor.py
> +                    weight = param['data']
done

2021-12-13 13:48 UTC, yeliang2258 commented on tests/auto_scan_test.py
> +                        data = shape()
done

2021-12-16 13:04 UTC, jiangjiajun requested changes

2021-12-16 13:04 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +            if input_shape[0] == -1:
为什么判断第0维为-1，第一维为-1不会出现吗

2021-12-16 13:32 UTC, yeliang2258 commented on paddle2onnx/op_mapper/tensor.py
> +            if input_shape[0] == -1:
done

2021-12-17 05:33 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +        if padding_idx != -1 and padding_idx != input_shape[0] - 1:
`padding_idx != input_shape[0] - 1`这个判断的用处是？

2021-12-17 05:35 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +        if padding_idx != -1 and padding_idx != input_shape[0] - 1:
也在PR上描述下这个bug问题情况和修复方法，不然每次都得再查一遍API来确认这个代码的修改原因

2021-12-17 06:24 UTC, yeliang2258 commented on paddle2onnx/op_mapper/tensor.py
> +        if padding_idx != -1 and padding_idx != input_shape[0] - 1:
好的，上面代码提交有问题，已经修改

2021-12-21 05:57 UTC, jiangjiajun approved these changes

2021-12-21 05:57 UTC, merged