Add testcase
PaddlePaddle/Paddle2ONNX pull request #430
Opened 2021-12-14 08:40 UTC by wjj19950828

## Do follow contributes
1、添加argmax/argmin单测
2、修复argmin在指定输出shape为int64时的bug
3、添加argmax对flatten属性支持

2021-12-17 05:40 UTC, jiangjiajun commented
MARK下，此PR在解决OpSet15问题后再合入

2022-03-11 08:31 UTC, jiangjiajun requested changes

2022-03-11 08:31 UTC, jiangjiajun commented on paddle2onnx/op_mapper/math.py
> +                'Reshape', inputs=[node.input('X', 0), const_value])
函数改为opset_7，因为在opset_1中， reshape中的shape是一个attr

2022-03-11 08:59 UTC, wjj19950828 commented on paddle2onnx/op_mapper/math.py
> +                'Reshape', inputs=[node.input('X', 0), const_value])
Done.

2022-03-11 08:59 UTC, wjj19950828 commented on paddle2onnx/op_mapper/math.py
> +                'Reshape', inputs=[node.input('X', 0), const_value])
Done.

2022-03-14 01:45 UTC, jiangjiajun approved these changes

2024-05-22 03:44 UTC, closed without merging