Add Clip testcases
PaddlePaddle/Paddle2ONNX pull request #436
Opened 2021-12-20 11:12 UTC by wjj19950828

## Do follow contributes
1、添加clip单测，包括4种情况：
- Max和Min都为attr
- Max为attr，Min为Tensor
- Max为Tensor，Min为attr
- Max和Min都为Tensor
2、修复clip相关bug

2021-12-21 02:27 UTC, jiangjiajun requested changes

2021-12-21 02:27 UTC, jiangjiajun commented on paddle2onnx/op_mapper/mapper_helper.py
> +            raise "When opset is less than 11, the input is not supported as float64 type."
clip不支持float64类型？确认下小于11时是否就无法对float64的tensor进行clip

2021-12-21 02:27 UTC, jiangjiajun commented on paddle2onnx/op_mapper/mapper_helper.py
> +            raise "When opset is less than 11, the input is not supported as float64 type."
raise "xxx" 这种语法是正确的吗，我看到上面也有类似这个代码，看起来可能会有问题

2021-12-21 02:27 UTC, jiangjiajun commented on paddle2onnx/op_mapper/mapper_helper.py
> +            if x_dtype == paddle.float64:
dtype如若只是传进去，这里两个if else代码可以精简一下，ONNX的dtype可以从paddle2onnx/constant/dtypes.py中的`DTYPE_PADDLE_ONNX_MAP`直接获取到对应的onnx dtype
例如代码可以直接写成
                min = graph.make_node(
                    'Constant',
                    attrs={'dtype': DTYPE_PADDLE_ONNX_MAP[x_dtype],
                           'value': min})

2021-12-21 02:27 UTC, jiangjiajun commented on paddle2onnx/op_mapper/math.py
> +                dtype = dtypes.ONNX.DOUBLE
同上面的评论，是否可以直接通过dict的映射，无需再加if判断

2021-12-21 02:27 UTC, jiangjiajun commented on paddle2onnx/op_mapper/math.py
> +                dtype = dtypes.ONNX.DOUBLE
同上

2021-12-21 02:27 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +                min_ = graph.make_node('Reshape', inputs=[min_, shape_tensor])
我看到当前的代码逻辑里面，是先将min reshape成[1]，然后在clip_helper里面，再squeeze成一个scalar tensor，这两步是否可以合为一步

2021-12-21 02:27 UTC, jiangjiajun commented on tests/auto_scan_test.py
> +                    elif input_type[j].count('int') > 0:
这里的代码修改是？

2021-12-21 07:48 UTC, wjj19950828 commented on paddle2onnx/op_mapper/mapper_helper.py
> +            raise "When opset is less than 11, the input is not supported as float64 type."
对的，在onnxruntime源码中已确认小于11时是否就无法对float64的tensor进行clip，仅支持float32类型，相关代码：https://github.com/microsoft/onnxruntime/blob/v1.10.0/onnxruntime/core/providers/cpu/math/clip.cc#L13

2021-12-21 07:49 UTC, wjj19950828 commented on paddle2onnx/op_mapper/mapper_helper.py
> +            raise "When opset is less than 11, the input is not supported as float64 type."
raise "xxx" 没有报错，会在opset_version<11时提示用户相关信息

2021-12-21 08:18 UTC, wjj19950828 commented on paddle2onnx/op_mapper/mapper_helper.py
> +            if x_dtype == paddle.float64:
Done.

2021-12-21 08:18 UTC, wjj19950828 commented on paddle2onnx/op_mapper/math.py
> +                dtype = dtypes.ONNX.DOUBLE
Done.

2021-12-21 08:18 UTC, wjj19950828 commented on paddle2onnx/op_mapper/math.py
> +                dtype = dtypes.ONNX.DOUBLE
Done.

2021-12-21 08:18 UTC, wjj19950828 commented on paddle2onnx/op_mapper/tensor.py
> +                min_ = graph.make_node('Reshape', inputs=[min_, shape_tensor])
Done.已去掉reshape op~

2021-12-21 08:20 UTC, wjj19950828 commented on tests/auto_scan_test.py
> +                    elif input_type[j].count('int') > 0:
这里是为了自定义数据生成，因为当min以及max为tensor时，目前单测框架无法保证min<max，所以需要自定义生成min以及max～

2021-12-21 08:25 UTC, wjj19950828 commented on tests/auto_scan_test.py
> +                    elif input_type[j].count('int') > 0:
参照叶梁的PR:https://github.com/PaddlePaddle/Paddle2ONNX/pull/423

2021-12-22 13:16 UTC, jiangjiajun commented on paddle2onnx/op_mapper/mapper_helper.py
> +            min = graph.make_node('Squeeze', min)
这里还有一个想法，如若min或max已经是一个scalar的时候，我们就无需再做处理了，paddle的min和max是否可以支持min或max为scalar tensor的情况

2021-12-22 13:21 UTC, jiangjiajun approved these changes

2021-12-22 13:39 UTC, wjj19950828 commented on paddle2onnx/op_mapper/mapper_helper.py
> +            min = graph.make_node('Squeeze', min)
并不支持，paddle的min以及max的shape必须为[1]
![image](https://user-images.githubusercontent.com/19977378/147101455-d1741033-f2e6-457d-8d44-c36dfaf52a57.png)

2021-12-23 02:28 UTC, merged