add cumsum test case
PaddlePaddle/Paddle2ONNX pull request #438
Opened 2021-12-22 03:31 UTC by neonhuang

add cumsum test case

2021-12-22 05:57 UTC, jiangjiajun requested changes

2021-12-22 05:57 UTC, jiangjiajun commented on tests/test_auto_scan_ cumsum.py
> +                min_size=4,
这里为啥min_size和max_size都一定需要为4呢

2021-12-22 06:03 UTC, yeliang2258 commented
单测文件名中间的空格删除一下

2021-12-22 12:57 UTC, neonhuang commented on tests/test_auto_scan_ cumsum.py
> +                min_size=4,
已经修复

2021-12-22 13:14 UTC, jiangjiajun approved these changes

2021-12-23 11:28 UTC, jiangjiajun approved these changes

2021-12-23 11:28 UTC, merged