add mul test case
PaddlePaddle/Paddle2ONNX pull request #439
Opened 2021-12-22 04:31 UTC by neonhuang

添加paddle.fluid.layers.mul单测，支持1～15

2021-12-22 13:23 UTC, jiangjiajun requested changes

2021-12-22 13:23 UTC, jiangjiajun commented on tests/test_auto_scan_mul.py
> +        x = paddle.fluid.layers.mul(inputs1, inputs2)
单测少了x_col_num_dims等参数的测试

2021-12-23 02:46 UTC, neonhuang commented on tests/test_auto_scan_mul.py
> +        x = paddle.fluid.layers.mul(inputs1, inputs2)
已经修复

2021-12-23 05:12 UTC, jiangjiajun approved these changes

2021-12-27 01:45 UTC, merged