add reduce_all test case and fix a bug
PaddlePaddle/Paddle2ONNX pull request #440
Opened 2021-12-22 08:34 UTC by neonhuang

1. 新增reduce_all单测
2. 修复opset > 12的时候，需要使用unsqueeze > 12的版本

2021-12-22 13:02 UTC, jiangjiajun requested changes

2021-12-22 13:02 UTC, jiangjiajun commented on paddle2onnx/op_mapper/math.py
> +                            'Unsqueeze', inputs=[unsqueeze_node] + [axes_node])
简写为inputs=[unsqueeze_node, axes_node]吧

2021-12-22 13:02 UTC, jiangjiajun commented on tests/test_auto_scan_reduce_all.py
> +                min_size=4,
是否能给一些不同的shape

2021-12-22 13:02 UTC, jiangjiajun commented on tests/test_auto_scan_reduce_all.py
> +                dim[0] = dim[0] - 1
dim加一下负数的情况

2021-12-23 03:26 UTC, neonhuang commented on paddle2onnx/op_mapper/math.py
> +                            'Unsqueeze', inputs=[unsqueeze_node] + [axes_node])
修复

2021-12-23 03:27 UTC, neonhuang commented on tests/test_auto_scan_reduce_all.py
> +                min_size=4,
修复

2021-12-23 04:40 UTC, neonhuang commented on tests/test_auto_scan_reduce_all.py
> +                dim[0] = dim[0] - 1
修复

2021-12-23 05:15 UTC, jiangjiajun approved these changes

2021-12-24 02:59 UTC, jiangjiajun approved these changes

2021-12-24 03:00 UTC, jiangjiajun approved these changes

2022-01-13 02:17 UTC, jiangjiajun requested changes

2022-01-13 02:17 UTC, jiangjiajun commented on paddle2onnx/op_mapper/math.py
> +            'Cast', inputs=[node.input('X', 0)], to=dtypes.ONNX.FLOAT)
这里改为cast成int32吧

2022-01-13 02:17 UTC, jiangjiajun commented on paddle2onnx/op_mapper/math.py
>              'Cast', inputs=[node.input('X', 0)], to=dtypes.ONNX.FLOAT)
同上

2022-01-13 02:45 UTC, jiangjiajun approved these changes

2022-01-13 08:59 UTC, merged