Reduce sum/min/mean/sum/prod
PaddlePaddle/Paddle2ONNX pull request #442
Opened 2021-12-23 03:02 UTC by neonhuang

1. 对Reduce sum/min/mean/sum/prod进行单测，并修复bug

2022-01-03 13:24 UTC, jiangjiajun requested changes

2022-01-03 13:24 UTC, jiangjiajun commented on paddle2onnx/op_mapper/math.py
> +            if graph.opset_version >= 13 and op_type == "ReduceSum":
这里重写一个新的opset函数吧，避免不同版本实现混在一起，增加后面维护的成本

2022-01-12 12:13 UTC, neonhuang commented on paddle2onnx/op_mapper/math.py
> +            if graph.opset_version >= 13 and op_type == "ReduceSum":
done

2022-01-13 02:53 UTC, jiangjiajun requested changes

2022-01-13 02:53 UTC, jiangjiajun commented on paddle2onnx/op_mapper/math.py
> +            if graph.opset_version >= 13 and op_type == "ReduceSum":
为什么还需要再判断graph.opset_version >= 13呢，这里不就是opset 13?

2022-01-13 02:53 UTC, jiangjiajun commented on paddle2onnx/op_mapper/math.py
> +                    })
代码太过冗余，上面的
`if need_unsqueese`和`else`中的代码几乎是一样的，唯一差别是多了一个unsqueeze，可以精简下代码

2022-01-13 04:52 UTC, neonhuang commented on paddle2onnx/op_mapper/math.py
> +                    })
修复

2022-01-13 04:52 UTC, neonhuang commented on paddle2onnx/op_mapper/math.py
> +            if graph.opset_version >= 13 and op_type == "ReduceSum":
修复

2022-01-13 08:19 UTC, jiangjiajun approved these changes

2022-01-14 02:09 UTC, merged