add layer_norm  test case and fix bug
PaddlePaddle/Paddle2ONNX pull request #449
Opened 2021-12-24 12:08 UTC by neonhuang

1. 新增layer_norm单测试
2. 支持float64
3. 修复weights, bias为空的bug

2022-01-14 02:28 UTC, jiangjiajun requested changes

2022-01-14 02:28 UTC, jiangjiajun commented on tests/test_auto_scan_instance_norm.py
> +            use_input_stats=True,
这里为什么一定要设为True

2022-01-14 02:28 UTC, jiangjiajun commented on tests/test_auto_scan_group_norm.py
> +        x = paddle.fluid.layers.nn.group_norm(
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/GroupNorm_cn.html#groupnorm GroupNorm有新版本的API

2022-01-14 02:28 UTC, jiangjiajun commented on tests/test_auto_scan_batch_norm.py
> +            use_global_stats=None)
这里如果是写死的参数，包括data_format, use_global_stats，确定是ONNX的BN不支持的原因后，在代码中添加assert，给出提示

2022-01-15 11:48 UTC, neonhuang commented on tests/test_auto_scan_instance_norm.py
> +            use_input_stats=True,
已经加上，不过这个use_input_stats，op转化实现那里没用到

2022-01-15 14:53 UTC, neonhuang commented on tests/test_auto_scan_batch_norm.py
> +            use_global_stats=None)
已经修改，onnx不支持NHWC, NLC, NDHWC这类型，只支持NC, NCL, NCHW, NCDHW

2022-01-17 02:10 UTC, neonhuang commented on tests/test_auto_scan_group_norm.py
> +        x = paddle.fluid.layers.nn.group_norm(
修复了

2022-01-17 09:36 UTC, merged