Add gather testcases
PaddlePaddle/Paddle2ONNX pull request #450
Opened 2021-12-24 13:20 UTC by wjj19950828

## Do follow contributes
1、添加gather单测
2、修复gather问题（3个）：增加axis属性、提示axis不能为tensor、GatherND的index_node必须为int64

2021-12-29 10:14 UTC, jiangjiajun requested changes

2021-12-29 10:14 UTC, jiangjiajun commented on paddle2onnx/op_mapper/math.py
> +            x = graph.make_node('Cast', inputs=x, to=dtypes.ONNX.FLOAT)
onnx的operator定义中看到是支持double的，为什么需要转呢

2021-12-29 12:16 UTC, wjj19950828 commented on paddle2onnx/op_mapper/math.py
> +            x = graph.make_node('Cast', inputs=x, to=dtypes.ONNX.FLOAT)
因为onnxruntime在transpose+matmul会优化走fusedmatmul这个kernel，目前这个kernel只支持float32,所以需要cast，已修改cast相关位置，参考链接：https://github.com/microsoft/onnxruntime/blob/ceb17f82ffc9f72acb64f28629d7db93d98e5ba9/onnxruntime/core/optimizer/matmul_transpose_fusion.cc#L200

2021-12-30 02:44 UTC, jiangjiajun requested changes

2021-12-30 02:44 UTC, jiangjiajun commented on paddle2onnx/op_mapper/activation.py
> +            raise Exception("Gelu does not support the input type as double")
这个应该提示为"float64"， 用户在上层定义模型时没有double的选项

2021-12-30 02:44 UTC, jiangjiajun commented on paddle2onnx/op_mapper/activation.py
> +            raise Exception("Gelu does not support the input type as double")
另外这个是否可以通过cast解决

2021-12-30 02:44 UTC, jiangjiajun commented on paddle2onnx/op_mapper/math.py
> +                y = graph.make_node('Cast', inputs=y, to=dtypes.ONNX.FLOAT)
这个cast，我觉得应该在这个if条件下，放在transpose前面
先前提到onnxruntime会将transpose+matmul进行fuse，所以会导出float64出错，但如果现在这样加了后变成transpose+cast+matmul，转换后的模型则无法命中fuse

如若改成 cat + transpose+matmul，则转换后仍然可以命中pass， 性能相对会更好

2021-12-30 02:44 UTC, jiangjiajun commented on paddle2onnx/op_mapper/math.py
> +                y = graph.make_node('Cast', inputs=y, to=dtypes.ONNX.FLOAT)
另外鉴于这里的bug是onnxruntime带来，当前逻辑只是为了迁就onnxruntime，在这里加上TODO，在onnxruntime修复后，我想我们可以移除掉这个逻辑

2021-12-30 09:39 UTC, wjj19950828 commented on paddle2onnx/op_mapper/activation.py
> +            raise Exception("Gelu does not support the input type as double")
Done.通过cast解决

2021-12-30 09:40 UTC, wjj19950828 commented on paddle2onnx/op_mapper/math.py
> +                y = graph.make_node('Cast', inputs=y, to=dtypes.ONNX.FLOAT)
Done.

2022-01-03 13:21 UTC, jiangjiajun requested changes

2022-01-03 13:21 UTC, jiangjiajun commented on paddle2onnx/op_mapper/activation.py
> +            Mul_node = graph.make_node('Mul', inputs=[x, zero_point_five])
变量名使用小写

2022-01-03 13:21 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +        if node.input('Axis', 0) != None:
当Axis为tensor时，可以先看是否可以直接获取这个tensor的值

2022-01-03 13:21 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +        if node.input('Axis', 0) != None:
同上

2022-01-06 09:10 UTC, wjj19950828 commented on paddle2onnx/op_mapper/activation.py
> +            Mul_node = graph.make_node('Mul', inputs=[x, zero_point_five])
Done.

2022-01-06 09:13 UTC, wjj19950828 commented on paddle2onnx/op_mapper/tensor.py
> +        if node.input('Axis', 0) != None:
Done.加入axis为paddle.to_tensor初始化tensor的实现.

2022-01-06 09:15 UTC, wjj19950828 commented on paddle2onnx/op_mapper/tensor.py
> +        if node.input('Axis', 0) != None:
Done.同上

2022-01-06 09:29 UTC, jiangjiajun requested changes

2022-01-06 09:29 UTC, jiangjiajun commented on paddle2onnx/op_mapper/math.py
> +            raise Exception("Erf does not support the input type as double")
这里提示也是一样，paddle在python层面，用户对double类型无感知，只知道float64。
相当于我们在使用api 
`paddle.create_variable(dtype='float64')`，如果不支持float64，应该提示的是float64不支持，而不是double不支持

2022-01-06 09:29 UTC, jiangjiajun commented on paddle2onnx/op_mapper/math.py
> +            raise Exception("Erf does not support the input type as double")
另外是否可以cast

2022-01-06 09:29 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +            axis = graph.parameters[axis_node].attribute[0].t.int32_data
axis_node是否存在parameter取不到的情况，如果取不到的话，这里会出异常出错吗

2022-01-06 09:29 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +                axis = graph.parameters[axis_node].attribute[0].t.int64_data[0]
同上

2022-01-06 09:29 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +        if axis == None:
axis is None

2022-01-06 09:29 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +        if axis == None:
同上

2022-01-06 09:29 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +            if index_dtype == paddle.int32:
这里是否改成 if index_dtype != paddle.int64更好，例如有其它的dtype?

2022-01-06 13:01 UTC, wjj19950828 commented on paddle2onnx/op_mapper/math.py
> +            raise Exception("Erf does not support the input type as double")
Done.通过cast解决

2022-01-06 13:03 UTC, wjj19950828 commented on paddle2onnx/op_mapper/tensor.py
> +            axis = graph.parameters[axis_node].attribute[0].t.int32_data
Done.取不到的话添加raise Exception，提示用户不支持axis为一个input tensor

2022-01-06 13:04 UTC, wjj19950828 commented on paddle2onnx/op_mapper/tensor.py
> +                axis = graph.parameters[axis_node].attribute[0].t.int64_data[0]
Done.同上

2022-01-06 13:04 UTC, wjj19950828 commented on paddle2onnx/op_mapper/tensor.py
> +        if axis == None:
Done.

2022-01-06 13:04 UTC, wjj19950828 commented on paddle2onnx/op_mapper/tensor.py
> +        if axis == None:
Done.

2022-01-06 13:04 UTC, wjj19950828 commented on paddle2onnx/op_mapper/tensor.py
> +            if index_dtype == paddle.int32:
Done.

2022-01-07 02:16 UTC, jiangjiajun requested changes

2022-01-07 02:16 UTC, jiangjiajun commented on paddle2onnx/op_mapper/math.py
> +        if x_dtype == paddle.float64:
确认一下，这里是只可能出现float64吗？

2022-01-07 02:16 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +            if graph.parameters[axis_node] is None:
axis_node是否会一定存在于graph.parameters里面，如果不存在，是否会有异常报错

2022-01-07 02:45 UTC, wjj19950828 commented on paddle2onnx/op_mapper/math.py
> +        if x_dtype == paddle.float64:
Done.paddle.erf确实仅支持float32以及float64，但还是修改为x_dtype != paddle.float32以及cast类型通过dtypes.DTYPE_PADDLE_ONNX_MAP映射

2022-01-07 02:47 UTC, wjj19950828 commented on paddle2onnx/op_mapper/tensor.py
> +            if graph.parameters[axis_node] is None:
Done.已修改为axis_node not in graph.parameters

2022-01-07 03:34 UTC, jiangjiajun requested changes

2022-01-07 03:34 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +                axis = graph.parameters[axis_node].attribute[0].t.int32_data
是否一定会在int32_data中，例如是否还在float_data int64_data int16_data

2022-01-07 03:36 UTC, jiangjiajun requested changes

2022-01-07 03:36 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +                axis = graph.parameters[axis_node].attribute[0].t.int32_data
看到下面有在处理了

2022-01-07 03:36 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +                axis = graph.parameters[axis_node].attribute[0].t.int32_data
这里有一个疑问，axis一定是从node中取的吗，会不会是一些weight之类的

2022-01-07 05:12 UTC, wjj19950828 commented on paddle2onnx/op_mapper/tensor.py
> +                axis = graph.parameters[axis_node].attribute[0].t.int32_data
weight应该不会，axis要么是输入节点，要么作为attr存在，正常状态下不应存在weight当中

2022-01-09 07:11 UTC, jiangjiajun approved these changes

2022-01-09 07:11 UTC, merged