some search op test case
PaddlePaddle/Paddle2ONNX pull request #458
Opened 2021-12-29 12:42 UTC by neonhuang

新增search op相关的op单测

2022-01-03 13:39 UTC, jiangjiajun requested changes

2022-01-03 13:39 UTC, jiangjiajun commented on tests/test_auto_scan_top_k.py
> +        x = paddle.fluid.layers.topk(input, k=self.config['k'])
`paddle.fluid.layers.topk`与`paddle.topk`是同一个吗

2022-01-03 13:39 UTC, jiangjiajun commented on tests/test_auto_scan_top_k.py
> +            "op_names": ["top_k_0"],
看到下面的代码了解了，这里调用的老版本的api是为了测老版本的OP，确认下，存在`top_k_0`这个OP吗

2022-01-03 13:39 UTC, jiangjiajun commented on tests/test_auto_scan_top_k_v2.py
> +            k=self.config['k'],
添加K为tensor的情况

不过在转换时，需要考虑这个k tensor为constant的情况，在这种情况下，我们应该直接从tensor中将值取出来

2022-01-03 13:39 UTC, jiangjiajun commented on tests/test_auto_scan_unique.py
> +            # dtype=self.config['xdtype']
dtype注释的原因是？

2022-01-04 07:14 UTC, neonhuang commented on tests/test_auto_scan_top_k.py
> +            "op_names": ["top_k_0"],
没有这个，代码是这样的：
   helper.append_op(
        **type="top_k",**
        inputs=inputs,
        outputs={"Out": [values],
                 "Indices": [indices]},
        attrs=attrs)
    values.stop_gradient = True
    indices.stop_gradient = True
    return values, indices
我现在改成这样了：
        config = {
            **"op_names": ["top_k"],**
            "test_data_shapes": [input_shape],
            "test_data_types": [[dtype]],
            "opset_version": [11, 15],
            "input_spec_shape": [],
            "k": k,
        }

2022-01-04 07:14 UTC, neonhuang commented on tests/test_auto_scan_top_k.py
> +        x = paddle.fluid.layers.topk(input, k=self.config['k'])
同下，解释了

2022-01-05 07:17 UTC, neonhuang commented on tests/test_auto_scan_top_k_v2.py
> +            k=self.config['k'],
修复

2022-01-05 07:17 UTC, neonhuang commented on tests/test_auto_scan_unique.py
> +            # dtype=self.config['xdtype']
目前这个op有diff,我暂时没测

2022-01-05 11:25 UTC, jiangjiajun commented on tests/test_auto_scan_unique.py
> +            # dtype=self.config['xdtype']
这个diff是指什么呢？是paddle的bug，还是paddle2onnx的bug，计划怎么来解决

2022-01-12 04:39 UTC, neonhuang commented on tests/test_auto_scan_unique.py
> +            # dtype=self.config['xdtype']
gpu有diff, cpu没diff, 后续再分析原因

2022-01-15 06:44 UTC, closed without merging