Add pow testcase
PaddlePaddle/Paddle2ONNX pull request #463
Opened 2021-12-31 07:21 UTC by wjj19950828

## Do follow contributes
1、添加pow op单测
2、修复ONNX Pow-7输入类型仅支持float和double问题，新增int32以及int64支持

2022-01-03 13:26 UTC, jiangjiajun requested changes

2022-01-03 13:26 UTC, jiangjiajun commented on paddle2onnx/op_mapper/activation.py
> +    support_opset_version_range = (9, 15)
PRelu不能从opset1开始支持吗

2022-01-03 13:26 UTC, jiangjiajun commented on paddle2onnx/op_mapper/math.py
>      def opset_8(cls, graph, node, **kw):
Pow同上

2022-01-04 09:25 UTC, wjj19950828 commented on paddle2onnx/op_mapper/activation.py
> +    support_opset_version_range = (9, 15)
这个因为里面会有expand op用于broadcast，expand op是opset_version>=8才支持，但目前prelu这个op是默认支持broadcast操作，已经将expand op去掉，目前支持7～15版本

2022-01-04 09:25 UTC, wjj19950828 commented on paddle2onnx/op_mapper/math.py
>      def opset_8(cls, graph, node, **kw):
同上，已修改～

2022-01-05 02:50 UTC, jiangjiajun requested changes
变量命名改后即可Approve

2022-01-05 02:50 UTC, jiangjiajun commented on paddle2onnx/op_mapper/activation.py
> +            onnx_node = graph.make_node('PRelu', inputs=[x, slope_node])
变量命名改一下，直接表明这个变量是啥，而非使用 onnx_node这种不明确含义的命名

2022-01-05 03:48 UTC, wjj19950828 commented on paddle2onnx/op_mapper/activation.py
> +            onnx_node = graph.make_node('PRelu', inputs=[x, slope_node])
Done.

2022-01-05 11:24 UTC, jiangjiajun approved these changes

2022-01-06 09:10 UTC, merged