add 16 个 Tensor op
PaddlePaddle/Paddle2ONNX pull request #464
Opened 2021-12-31 08:24 UTC by neonhuang

2022-01-03 13:51 UTC, jiangjiajun requested changes

2022-01-03 13:51 UTC, jiangjiajun commented on tests/test_auto_scan_assign.py
> +        x = paddle.assign(inputs)
添加inputs为`Tensor|np.ndarray|list|tuple|scalar`的测试

2022-01-03 13:51 UTC, jiangjiajun commented on tests/test_auto_scan_concat.py
> +    def forward(self, inputs, inputs_):
这里函数的参数命名`inputs`和`inputs_`的原因是？如若没有特殊的原因，改成`input_0`, `input_1`

2022-01-03 13:51 UTC, jiangjiajun commented on tests/test_auto_scan_expand_v2.py
> +        x = paddle.expand(inputs, shape=[2, 3, 10])
添加shape为`tuple|list|Tensor`的测试

2022-01-03 13:51 UTC, jiangjiajun commented on tests/test_auto_scan_meshgrid.py
> +    def forward(self, inputs, _inputs):
这里函数参数命名为`inputs`和`_inputs`的原因是什么？与上面的函数参数命名看起来不同，这种命名方式感觉很糟糕，无法让人一眼看明这俩参数的作用

2022-01-03 13:51 UTC, jiangjiajun commented on tests/test_auto_scan_scatter.py
> +    def forward(self, inputs, _index, _updates):
这里命名中前面加下划线的原因是？

2022-01-05 09:10 UTC, yeliang2258 commented
请解决一下冲突

2022-01-06 08:12 UTC, yeliang2258 requested changes

2022-01-06 08:12 UTC, yeliang2258 commented on tests/test_auto_scan_meshgrid.py
> +        input_shape = [3]
直接赋值为3的原因是？

2022-01-09 07:10 UTC, neonhuang commented on tests/test_auto_scan_concat.py
> +    def forward(self, inputs, inputs_):
已经修复

2022-01-09 07:15 UTC, neonhuang commented on tests/test_auto_scan_assign.py
> +        x = paddle.assign(inputs)
已经添加

2022-01-09 07:16 UTC, neonhuang commented on tests/test_auto_scan_meshgrid.py
> +    def forward(self, inputs, _inputs):
已经修改

2022-01-09 07:17 UTC, neonhuang commented on tests/test_auto_scan_scatter.py
> +    def forward(self, inputs, _index, _updates):
已经修改

2022-01-11 11:42 UTC, neonhuang commented on tests/test_auto_scan_meshgrid.py
> +        input_shape = [3]
修复

2022-01-15 07:25 UTC, closed without merging