add test for yolobox
PaddlePaddle/Paddle2ONNX pull request #473
Opened 2022-01-05 09:04 UTC by yeliang2258

1. 增加yolo_box的单测，增加opset version 12到15的支持，支持float64输入支持(onnxruntime的Split不支持float64)
2. onnxbase支持多个输出的检测支持
3. 修复graph中的拼写错误

2022-01-13 12:10 UTC, jiangjiajun requested changes

2022-01-13 12:10 UTC, jiangjiajun commented on paddle2onnx/op_mapper/detection/yolo_box.py
> +        print("get yolo_box op")
删除

2022-01-18 06:36 UTC, yeliang2258 commented on paddle2onnx/op_mapper/detection/yolo_box.py
> +        print("get yolo_box op")
done

2022-02-12 07:57 UTC, jiangjiajun requested changes

2022-02-12 07:57 UTC, jiangjiajun commented on paddle2onnx/op_mapper/detection/yolo_box.py
> +            if graph.opset_version < 11:
这里的分支为何没有使用clip_helper?

2022-02-12 08:10 UTC, yeliang2258 commented
clip helper是之后添加的，我改一下



---Original---
From: ***@***.***&gt;
Date: Sat, Feb 12, 2022 15:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PaddlePaddle/Paddle2ONNX] add test for yolobox (PR #473)




 
@jiangjiajun requested changes on this pull request.
 
 
In paddle2onnx/op_mapper/detection/yolo_box.py:
 &gt; + +            node_new_img_height = graph.make_node( +                'Sub', inputs=[node_img_height_cast, node_number_one]) + +            node_new_img_width = graph.make_node( +                'Sub', inputs=[node_img_width_cast, node_number_one]) + +            cls.node_pred_box_x2_sub_w = graph.make_node( +                'Sub', +                inputs=[cls.node_pred_box_x2_decode, node_new_img_width]) + +            cls.node_pred_box_y2_sub_h = graph.make_node( +                'Sub', +                inputs=[cls.node_pred_box_y2_decode, node_new_img_height]) + +            if graph.opset_version < 11:  
这里的分支为何没有使用clip_helper?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2022-02-16 06:33 UTC, yeliang2258 commented on paddle2onnx/op_mapper/detection/yolo_box.py
> +            if graph.opset_version < 11:
done

2022-03-02 11:24 UTC, jiangjiajun approved these changes

2022-03-23 04:28 UTC, merged