Add gather_nd and its tests
PaddlePaddle/Paddle2ONNX pull request #479
Opened 2022-01-11 03:46 UTC by yeliang2258

增加gather_nd的转换和对应的单测。
相关issue：https://github.com/PaddlePaddle/Knover/issues/106

2022-01-11 04:42 UTC, fadelma commented
Hello, I got this error when trying to convert the NSP model of PLATO-2 32L
```
2022-01-11 04:33:16 [INFO]      ONNX model generated is valid.
Traceback (most recent call last):
  File "/mnt/data3/shared_envs/paddle_env/lib/python3.9/site-packages/paddle2onnx-0.9.0-py3.9.egg/paddle2onnx/utils.py", line 43, in check_model
  File "/mnt/data3/shared_envs/paddle_env/lib/python3.9/site-packages/onnx/checker.py", line 101, in check_model
    protobuf_string = model.SerializeToString()
ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 6530750548

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data3/shared_envs/paddle_env/bin/paddle2onnx", line 33, in <module>
    sys.exit(load_entry_point('paddle2onnx==0.9.0', 'console_scripts', 'paddle2onnx')())
  File "/mnt/data3/shared_envs/paddle_env/lib/python3.9/site-packages/paddle2onnx-0.9.0-py3.9.egg/paddle2onnx/command.py", line 187, in main
  File "/mnt/data3/shared_envs/paddle_env/lib/python3.9/site-packages/paddle2onnx-0.9.0-py3.9.egg/paddle2onnx/command.py", line 151, in program2onnx
  File "/mnt/data3/shared_envs/paddle_env/lib/python3.9/site-packages/paddle2onnx-0.9.0-py3.9.egg/paddle2onnx/convert.py", line 83, in program2onnx
  File "/mnt/data3/shared_envs/paddle_env/lib/python3.9/site-packages/paddle2onnx-0.9.0-py3.9.egg/paddle2onnx/convert.py", line 37, in export_onnx
  File "/mnt/data3/shared_envs/paddle_env/lib/python3.9/site-packages/paddle2onnx-0.9.0-py3.9.egg/paddle2onnx/graph/onnx_graph.py", line 234, in export_proto
  File "/mnt/data3/shared_envs/paddle_env/lib/python3.9/site-packages/paddle2onnx-0.9.0-py3.9.egg/paddle2onnx/utils.py", line 45, in check_model
Exception: ONNX model is not valid.
```

2022-01-11 06:19 UTC, jiangjiajun requested changes

2022-01-11 06:19 UTC, jiangjiajun commented on tests/test_auto_scan_gather_nd.py
> +            "opset_version": [15],
opset应该也要包括11？

2022-01-11 06:27 UTC, yeliang2258 commented on tests/test_auto_scan_gather_nd.py
> +            "opset_version": [15],
不用，减少时间CI时间，11之后这个OP一直没变过，刚才我加了11，也是可以通过的

2022-01-11 06:38 UTC, yeliang2258 commented
> Hello, I got this error when trying to convert the NSP model of PLATO-2 32L
> 
> ```
> 2022-01-11 04:33:16 [INFO]      ONNX model generated is valid.
> Traceback (most recent call last):
>   File "/mnt/data3/shared_envs/paddle_env/lib/python3.9/site-packages/paddle2onnx-0.9.0-py3.9.egg/paddle2onnx/utils.py", line 43, in check_model
>   File "/mnt/data3/shared_envs/paddle_env/lib/python3.9/site-packages/onnx/checker.py", line 101, in check_model
>     protobuf_string = model.SerializeToString()
> ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 6530750548
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/mnt/data3/shared_envs/paddle_env/bin/paddle2onnx", line 33, in <module>
>     sys.exit(load_entry_point('paddle2onnx==0.9.0', 'console_scripts', 'paddle2onnx')())
>   File "/mnt/data3/shared_envs/paddle_env/lib/python3.9/site-packages/paddle2onnx-0.9.0-py3.9.egg/paddle2onnx/command.py", line 187, in main
>   File "/mnt/data3/shared_envs/paddle_env/lib/python3.9/site-packages/paddle2onnx-0.9.0-py3.9.egg/paddle2onnx/command.py", line 151, in program2onnx
>   File "/mnt/data3/shared_envs/paddle_env/lib/python3.9/site-packages/paddle2onnx-0.9.0-py3.9.egg/paddle2onnx/convert.py", line 83, in program2onnx
>   File "/mnt/data3/shared_envs/paddle_env/lib/python3.9/site-packages/paddle2onnx-0.9.0-py3.9.egg/paddle2onnx/convert.py", line 37, in export_onnx
>   File "/mnt/data3/shared_envs/paddle_env/lib/python3.9/site-packages/paddle2onnx-0.9.0-py3.9.egg/paddle2onnx/graph/onnx_graph.py", line 234, in export_proto
>   File "/mnt/data3/shared_envs/paddle_env/lib/python3.9/site-packages/paddle2onnx-0.9.0-py3.9.egg/paddle2onnx/utils.py", line 45, in check_model
> Exception: ONNX model is not valid.
> ```

hello, According to the official documentation of onnx, you can turn off the model check function during conversion, and then use the following command to check the model after the model is saved.
Model conversion command:
> ```
>paddle2onnx --model_dir paddle_model  --save_file onnx_file --opset_version 11 --enable_onnx_checker False
> ```

Model check command:
> ```
>import onnx
>onnx.checker.check_model('path/to/the/model.onnx')
> ```
Related document：https://github.com/onnx/onnx/blob/main/docs/PythonAPIOverview.md#checking-a-large-onnx-model-2gb
![image](https://user-images.githubusercontent.com/30516196/148892977-ec320d50-adf4-45b1-b177-fab0b733c66b.png)

2022-01-12 02:10 UTC, jiangjiajun approved these changes

2022-01-12 08:06 UTC, merged