Add softmax_with_cross_entropy testcases
PaddlePaddle/Paddle2ONNX pull request #483
Opened 2022-01-13 14:38 UTC by wjj19950828

## Do follow contributes
1、新增softmax_with_cross_entropy单测
2、重写softmax_with_cross_entropy实现，增加return_softmax为True的支持
3、增加多输出比较支持

2022-01-14 02:17 UTC, jiangjiajun requested changes

2022-01-14 02:17 UTC, jiangjiajun commented on tests/test_auto_scan_softmax_with_cross_entropy.py
> +            "return_softmax": False,
这个为啥只能设成False

2022-01-14 08:23 UTC, wjj19950828 commented on tests/test_auto_scan_softmax_with_cross_entropy.py
> +            "return_softmax": False,
Done.
True和False均可支持，但为True时，onnx返回为log(softmax),paddle为softmax，故最后需加一个exp op

2022-01-16 07:36 UTC, jiangjiajun approved these changes

2022-01-16 07:37 UTC, merged