add 6 search operators test case
PaddlePaddle/Paddle2ONNX pull request #486
Opened 2022-01-15 07:04 UTC by neonhuang

新增7个search op和单测:
1.1. argsort: 修复对于 opset < 11的情况，增加不支持int32, int64的判断, 
主要原因是该op使用的TopK在这个opset不支持int32和int64
1.2. index_select: 无修改
1.3. masked_select: 无修改，
1.4. top_k: 无修改，
1.5. where: 无修改，
1.6. where_index : 无修改

2022-01-17 06:24 UTC, jiangjiajun requested changes

2022-01-17 06:24 UTC, jiangjiajun commented on paddle2onnx/op_mapper/search.py
> +            )
这里可以先cast来解决

2022-01-17 10:05 UTC, neonhuang commented on paddle2onnx/op_mapper/search.py
> +            )
修复

2022-01-18 01:55 UTC, jiangjiajun approved these changes

2022-01-18 07:10 UTC, merged