add 6 tensor op(concat/shape/size/stack/meshgrid/pixel_shuffle) and test case
PaddlePaddle/Paddle2ONNX pull request #487
Opened 2022-01-15 08:06 UTC by neonhuang

concat: 修复concat可以支持float16, float64, 同时修复axis为tensor的情况
size: 支持opset > 12的场景，另外1-5不支持float16
stack: 修复opset>12的情况
shape: 无修改，由于该op中使用了cast，因此目前不支持float16
meshgrid: 无修改
pixel_shuffle: 无修改

2022-01-16 07:47 UTC, jiangjiajun requested changes

2022-01-16 07:47 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +            axes = graph.parameters[axes_node].attribute[0].t.int64_data
这里从tensor中取值的操作，参考下这个PR https://github.com/PaddlePaddle/Paddle2ONNX/pull/450
![image](https://user-images.githubusercontent.com/19339784/149651671-53e145f4-780d-4f19-a1ab-99793b92da23.png)
![image](https://user-images.githubusercontent.com/19339784/149651692-ad5ae877-d11b-4ffc-ac7d-5069ffeaec05.png)

2022-01-17 02:37 UTC, neonhuang commented on paddle2onnx/op_mapper/tensor.py
> +            axes = graph.parameters[axes_node].attribute[0].t.int64_data
修复了

2022-01-17 06:19 UTC, jiangjiajun requested changes

2022-01-17 06:19 UTC, jiangjiajun commented on tests/test_auto_scan_meshgrid.py
> +
meshigrid再加上3个、5个输入Tensor的测试吧

2022-01-17 07:41 UTC, neonhuang commented on tests/test_auto_scan_meshgrid.py
> +
不行的。该OP的输入是张量或者包含张量的列表, 包含 k 个一维张量，对每个张量做扩充操作，输出 k 个 k 维张量。

2022-01-17 12:37 UTC, jiangjiajun approved these changes

2022-01-18 01:34 UTC, merged