add auto_upset_version choice
PaddlePaddle/Paddle2ONNX pull request #489
Opened 2022-01-16 08:40 UTC by yeliang2258

1. add auto_upset_version choice
2. set auto_upset_version=False in auto_scan_test.
3.

2022-01-16 11:05 UTC, jiangjiajun approved these changes

2022-01-16 11:06 UTC, jiangjiajun requested changes
CI没过

2022-01-16 11:17 UTC, yeliang2258 commented
没有auto update之后，logsumexp、PixelShuffle和topk的opset version设置有问题，导致的CI没过。

2022-01-17 02:14 UTC, jiangjiajun approved these changes

2022-01-17 05:59 UTC, merged