Slice op
PaddlePaddle/Paddle2ONNX pull request #494
Opened 2022-01-18 13:01 UTC by neonhuang

修复slice/stride_slice op

2022-01-19 02:35 UTC, jiangjiajun requested changes

2022-01-19 02:35 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +        if strides is not None and len(node.input('StridesTensor')) > 0:
这里用的条件是指strides在属性中，同时也是一个输入？
另外strides是slice OP的一个属性或输入吗
如果为属性，是否strides为1的时候，其实是可以支持的

2022-01-19 02:35 UTC, jiangjiajun commented on tests/test_auto_scan_slice.py
> +        x = paddle.slice(inputs, axes=axes, starts=starts, ends=ends)
添加以下几种测试情况
- 1. inputs_shape: [a, b, c, d]  axes=[0, 3], starts=[1, 0], ends=[a, c]  
- 2. inputs_shape: [a, b, c, d]  axes=[0, 1, 2, 3], starts=[1, 0, 0, 0], ends=[a+10, b+10, c+10, d+10]  
- 3. inputs_shape: [a, b, d, d] axes=[0, 1], starts=[1, tensor(0)], ends=[tensor(a), c]

2022-01-19 03:14 UTC, neonhuang commented on paddle2onnx/op_mapper/tensor.py
> +        if strides is not None and len(node.input('StridesTensor')) > 0:
strides = node.attr('strides'), 这是strided_slice的属性，slice没有；在跑slice的时候，strides是为None的；

2022-01-19 03:36 UTC, neonhuang commented on tests/test_auto_scan_slice.py
> +        x = paddle.slice(inputs, axes=axes, starts=starts, ends=ends)
inputs_shape: [a, b, d, d] axes=[0, 1], starts=[1, tensor(0)], ends=[tensor(a), c], 这种case，在模型动转静的时候会报错

2022-01-19 06:38 UTC, neonhuang commented on tests/test_auto_scan_slice.py
> +        x = paddle.slice(inputs, axes=axes, starts=starts, ends=ends)
iii添加了

2022-01-19 07:43 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +        if strides is not None and len(node.input('StridesTensor')) > 0:
是否是确认的情况，如若是确认的话，是否直接在slice中给assert掉属性stride一定要为None，而不用写那么长的代码

2022-01-19 12:18 UTC, jiangjiajun requested changes

2022-01-19 12:18 UTC, jiangjiajun commented on tests/test_auto_scan_slice.py
> +        ends = [10, 10, paddle.to_tensor(10), 10]
添加某个为scalar tensor的情况，例如

ends = [10, 10, paddle.to_tensor(np.array(10).astype("int64")), 10]

2022-01-20 03:14 UTC, neonhuang commented on paddle2onnx/op_mapper/tensor.py
> +        if strides is not None and len(node.input('StridesTensor')) > 0:
done

2022-01-20 09:54 UTC, neonhuang commented on tests/test_auto_scan_slice.py
> +        ends = [10, 10, paddle.to_tensor(10), 10]
修复

2022-01-24 02:27 UTC, jiangjiajun requested changes

2022-01-24 02:27 UTC, jiangjiajun commented on paddle2onnx/op_mapper/mapper_helper.py
> +    max_dim = 1 if max_dim == 0 else max_dim
只支持max_dim = 1 or max_dim = 0

2022-01-24 10:27 UTC, neonhuang commented on paddle2onnx/op_mapper/mapper_helper.py
> +    max_dim = 1 if max_dim == 0 else max_dim
修复

2022-01-25 13:13 UTC, jiangjiajun requested changes

2022-01-25 13:13 UTC, jiangjiajun commented on paddle2onnx/op_mapper/mapper_helper.py
> +            "Try converting with opset_version > { } ".format(
语法错误

2022-01-25 13:13 UTC, jiangjiajun commented on paddle2onnx/op_mapper/mapper_helper.py
> +            "Try converting with opset_version > { } ".format(
传入一个要转换的OP名称吧，这样提示更明确

2022-01-25 13:15 UTC, jiangjiajun requested changes

2022-01-25 13:15 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +                       node_tensor_list_name, tensor_name):
tensor_name改为attr_name

2022-01-26 06:36 UTC, neonhuang commented on paddle2onnx/op_mapper/tensor.py
> +                       node_tensor_list_name, tensor_name):
done

2022-01-26 07:42 UTC, jiangjiajun requested changes

2022-01-26 07:42 UTC, jiangjiajun commented on tests/test_auto_scan_slice.py
> +        x = paddle.slice(inputs, axes=axes, starts=starts, ends=ends)
少了decrease_axis的情况
```
def forward(input):
    return input[1:2, 2, :]
```

2022-01-26 07:42 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +            axis = mapper_helper.get_value_from_parameters(graph, axis_node)[0]
axis_node改为传入正在转换哪个OP，便于出错时，定位是哪个OP导致

2022-01-26 07:42 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +            axis = mapper_helper.get_value_from_parameters(graph, axis_node)[0]
try:
    axis = mapper_helper.get_value_from_parameters(graph, axis_node)[0]
except Exception as e:
     raise("Currently does not support the axis parameter as input tensor")

2022-01-26 07:55 UTC, neonhuang commented on tests/test_auto_scan_slice.py
> +        x = paddle.slice(inputs, axes=axes, starts=starts, ends=ends)
done

2022-01-26 09:13 UTC, neonhuang commented on paddle2onnx/op_mapper/tensor.py
> +            axis = mapper_helper.get_value_from_parameters(graph, axis_node)[0]
done

2022-01-26 09:13 UTC, neonhuang commented on paddle2onnx/op_mapper/mapper_helper.py
> +            "Try converting with opset_version > { } ".format(
done

2022-01-26 11:33 UTC, jiangjiajun approved these changes

2022-02-07 05:17 UTC, merged