Squeeze op
PaddlePaddle/Paddle2ONNX pull request #496
Opened 2022-01-19 07:47 UTC by neonhuang

1. 修复类似shape为[2,3,2]这种case
2. 修复axis为空的情况的case

2022-01-24 02:08 UTC, jiangjiajun requested changes

2022-01-24 02:08 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +        if axes is not None:
为什么要判断is not None，看下面也没有对应的else

2022-01-24 02:08 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +        if axes is not None:
同上

2022-01-24 04:36 UTC, neonhuang commented on paddle2onnx/op_mapper/tensor.py
> +        if axes is not None:
不需要了。如果is None的时候，返回值已经函数compute_axes里面返回了
    def compute_axes(cls, graph, node):
        shape = node.input_shape('X', 0)
        ret = [i for i, val in enumerate(shape) if val > 1]
        if len(ret) == len(shape):
            graph.make_node(
                'Identity', inputs=node.input('X'), **outputs=node.output('Out')**)
            return None
        else:
            axes = node.attr('axes')
            if len(axes) > 0:
                axes = [
                    axis + len(shape) if axis < 0 else axis
                    for i, axis in enumerate(axes)
                ]
            return axes

2022-01-24 04:36 UTC, neonhuang commented on paddle2onnx/op_mapper/tensor.py
> +        if axes is not None:
同上

2022-01-24 09:25 UTC, neonhuang commented on paddle2onnx/op_mapper/tensor.py
> +        if axes is not None:
修复

2022-01-24 09:25 UTC, neonhuang commented on paddle2onnx/op_mapper/tensor.py
> +        if axes is not None:
修复

2022-01-25 05:11 UTC, jiangjiajun requested changes

2022-01-25 05:11 UTC, jiangjiajun commented on tests/test_auto_scan_squeeze2.py
> +            "test_data_types": [[dtype]],
添加datatype float32、float64、bool、int8、int32、int64

2022-01-25 06:02 UTC, neonhuang commented on tests/test_auto_scan_squeeze2.py
> +            "test_data_types": [[dtype]],
添加

2022-01-27 01:56 UTC, jiangjiajun commented on tests/test_auto_scan_squeeze2.py
> +            "input_spec_shape": [],
将input_spec_shape设为全动态

2022-02-07 03:33 UTC, neonhuang commented on tests/test_auto_scan_squeeze2.py
> +            "input_spec_shape": [],
添加

2022-02-07 04:37 UTC, jiangjiajun approved these changes

2022-02-07 06:01 UTC, neonhuang commented on tests/test_auto_scan_squeeze2.py
> +            "input_spec_shape": [],
done

2022-02-07 07:50 UTC, merged