add Expand v2 op test case
PaddlePaddle/Paddle2ONNX pull request #498
Opened 2022-01-19 13:14 UTC by neonhuang

新增expand_v2单测

2022-01-20 03:01 UTC, yeliang2258 commented
还有bug尚未修复

2022-02-07 02:14 UTC, jiangjiajun commented
待slice合入

2022-02-09 06:30 UTC, jiangjiajun requested changes

2022-02-09 06:30 UTC, jiangjiajun commented on tests/test_auto_scan_expand_v2.py
> +            shape = paddle.to_tensor(np.array(shape).astype("int32"))
加一个分支
```
if self.config['shape_is_int64']:
    shape = paddle.to_tensor(np.array(shape).astype("int64"))
```

2022-02-09 06:30 UTC, jiangjiajun commented on tests/test_auto_scan_expand_v2.py
> +        ]
同上，另外无需的注释代码删除

2022-02-09 07:18 UTC, neonhuang commented on tests/test_auto_scan_expand_v2.py
> +        ]
done

2022-02-09 07:18 UTC, neonhuang commented on tests/test_auto_scan_expand_v2.py
> +            shape = paddle.to_tensor(np.array(shape).astype("int32"))
done

2022-02-09 09:30 UTC, jiangjiajun approved these changes

2022-02-09 09:31 UTC, merged