Scale op
PaddlePaddle/Paddle2ONNX pull request #506
Opened 2022-01-21 04:03 UTC by neonhuang

1.支持scale为tensor的情形
2.支持float64
3. int32, int64, 这个op有diff, 分析发现是paddle的问题

2022-01-24 01:57 UTC, jiangjiajun requested changes

2022-01-24 01:57 UTC, jiangjiajun commented on paddle2onnx/op_mapper/math.py
> +                scale_node = graph.make_node(
cast改为根据情况再添加，没必要所有的scale都需要cast

2022-01-24 02:00 UTC, jiangjiajun requested changes

2022-01-24 02:00 UTC, jiangjiajun commented on paddle2onnx/op_mapper/math.py
> +        if len(node.input('ScaleTensor')) == 0 and np.fabs(
opset1的这个函数直接删除吧

2022-01-24 04:26 UTC, neonhuang commented on paddle2onnx/op_mapper/math.py
> +                scale_node = graph.make_node(
修复

2022-01-24 04:32 UTC, neonhuang commented on paddle2onnx/op_mapper/math.py
> +        if len(node.input('ScaleTensor')) == 0 and np.fabs(
修复

2022-01-24 05:35 UTC, jiangjiajun requested changes

2022-01-24 05:35 UTC, jiangjiajun commented on paddle2onnx/op_mapper/mapper_helper.py
> +def clip_helper(graph, node, input, max, min, output=[],
改动了clip_helper，全局搜一下用到clip_helper的地方

2022-01-24 09:12 UTC, neonhuang commented on paddle2onnx/op_mapper/mapper_helper.py
> +def clip_helper(graph, node, input, max, min, output=[],
全局搜了

2022-01-25 01:48 UTC, jiangjiajun approved these changes

2022-01-25 01:48 UTC, merged