add Expand/ tile test case
PaddlePaddle/Paddle2ONNX pull request #507
Opened 2022-01-23 02:35 UTC by neonhuang

1.新增expand/tile test case

2022-02-07 02:14 UTC, jiangjiajun commented
需等slice合入，再整理代码，重新commit

2022-02-09 06:51 UTC, jiangjiajun requested changes

2022-02-09 06:51 UTC, jiangjiajun commented on tests/test_auto_scan_expand.py
> +                np.array(expand_times).astype('int32'))
增加dtype为int64的测试

2022-02-09 06:51 UTC, jiangjiajun commented on tests/test_auto_scan_expand.py
> +        expand_times = [4, 3, paddle.to_tensor(np.array(2).astype("int64")), 1]
增加这个tensor为int32的单测

2022-02-09 06:51 UTC, jiangjiajun commented on tests/test_auto_scan_tile.py
> +                np.array(repeat_times).astype('int32'))
同上

2022-02-09 06:51 UTC, jiangjiajun commented on tests/test_auto_scan_tile.py
> +        repeat_times = [4, paddle.to_tensor(3), 2, 1]
同上

2022-02-09 07:50 UTC, neonhuang commented on tests/test_auto_scan_expand.py
> +                np.array(expand_times).astype('int32'))
done

2022-02-09 07:50 UTC, neonhuang commented on tests/test_auto_scan_expand.py
> +        expand_times = [4, 3, paddle.to_tensor(np.array(2).astype("int64")), 1]
done

2022-02-09 07:50 UTC, neonhuang commented on tests/test_auto_scan_tile.py
> +                np.array(repeat_times).astype('int32'))
done

2022-02-09 07:50 UTC, neonhuang commented on tests/test_auto_scan_tile.py
> +        repeat_times = [4, paddle.to_tensor(3), 2, 1]
done

2022-02-10 01:59 UTC, jiangjiajun approved these changes

2022-02-10 02:00 UTC, merged