Support clip op for float64
PaddlePaddle/Paddle2ONNX pull request #512
Opened 2022-01-24 14:06 UTC by wjj19950828

## Do follow contributes
1、关于clip op float64类型去掉相关assert，通过cast float32解决
2、增加float64 单测

2022-01-24 15:02 UTC, jiangjiajun requested changes

2022-01-24 15:02 UTC, jiangjiajun commented on paddle2onnx/op_mapper/mapper_helper.py
>              input = graph.make_node(
单测增加对应的测试

2022-01-25 03:21 UTC, wjj19950828 commented on paddle2onnx/op_mapper/mapper_helper.py
>              input = graph.make_node(
Done.
相应增加了两种单测：
1、输入类型为float64
2、min和max为tensor时，输入类型不一致问题
另外因为node作为参数传入clip_helper函数，将x_dtype作为参数传到函数变为直接在clip_helper中获取

2022-01-25 05:20 UTC, jiangjiajun commented on paddle2onnx/op_mapper/mapper_helper.py
>              input = graph.make_node(
才注意到原来的接口中还存在x_dtype这个参数，这个确实得应该在clip_helper中修改。

clip_helper在多个地方都有调用，全局搜索确认下是否还有其它地方需要修改

2022-01-25 05:22 UTC, wjj19950828 commented on paddle2onnx/op_mapper/mapper_helper.py
>              input = graph.make_node(
已全局搜索确认，相应都已完成修改～

2022-01-25 06:26 UTC, jiangjiajun approved these changes

2022-01-25 06:26 UTC, merged