add Roll op
PaddlePaddle/Paddle2ONNX pull request #513
Opened 2022-01-25 03:46 UTC by neonhuang

新增roll op

2022-01-25 11:17 UTC, jiangjiajun requested changes

2022-01-25 11:17 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +                    ends=[maxsize])
这里的maxsize设置为60000吧，之前遇到数据太大，会导致无法正常进行TensorRT的半精度推理

2022-01-27 06:18 UTC, neonhuang commented on paddle2onnx/op_mapper/tensor.py
> +                    ends=[maxsize])
done

2022-02-07 02:13 UTC, jiangjiajun commented
需添加为tensor的情况

2022-02-17 02:20 UTC, jiangjiajun requested changes

2022-02-17 02:20 UTC, jiangjiajun commented on tests/test_auto_scan_roll.py
> +            opset_version = [10, 12, 15]
OP 测试版本改成[10, 11, 12, 13, 14, 15]吧, 后面会从最低版本开始测，一直测到15

2022-02-17 02:20 UTC, jiangjiajun commented on tests/test_auto_scan_roll.py
> +            opset_version = [7, 9, 15]
同上

2022-02-17 02:28 UTC, neonhuang commented on tests/test_auto_scan_roll.py
> +            opset_version = [10, 12, 15]
done

2022-02-17 02:29 UTC, neonhuang commented on tests/test_auto_scan_roll.py
> +            opset_version = [7, 9, 15]
done

2022-02-17 05:00 UTC, merged