Cpp auto scan test dev
PaddlePaddle/Paddle2ONNX pull request #529
Opened 2022-02-09 12:25 UTC by yeliang2258

1. Add auto scan test.

2022-02-09 14:14 UTC, jiangjiajun requested changes

2022-02-09 14:14 UTC, jiangjiajun commented on paddle2onnx/parser/parser.hpp
> +      _blocks_ops[i].reserve(prog->blocks(i).ops_size());
为啥需要reverse

2022-02-09 14:17 UTC, yeliang2258 commented
这个就是预先分配一下内存，略微加速而已，加不加影响不大



---Original---
From: ***@***.***&gt;
Date: Wed, Feb 9, 2022 22:14 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PaddlePaddle/Paddle2ONNX] Cpp auto scan test dev (PR #529)




 
@jiangjiajun requested changes on this pull request.
 
 
In paddle2onnx/parser/parser.hpp:
 &gt; @@ -133,6 +133,7 @@ struct PaddleParser {      _blocks_ops.clear();      _blocks_ops.resize(prog-&gt;blocks_size());      for (auto i = 0; i < prog-&gt;blocks_size(); ++i) { +      _blocks_ops[i].reserve(prog-&gt;blocks(i).ops_size());  
为啥需要reverse
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2022-02-09 16:19 UTC, jiangjiajun commented on paddle2onnx/parser/parser.hpp
> +      _blocks_ops[i].reserve(prog->blocks(i).ops_size());
原来如此，我看成reverse了

2022-02-10 02:06 UTC, jiangjiajun approved these changes

2022-02-10 02:06 UTC, merged