add elementwise op and tests
PaddlePaddle/Paddle2ONNX pull request #539
Opened 2022-02-11 07:46 UTC by yeliang2258

1. add elementwise ops：elementwise_add、elementwise_sub、elementwise_div、elementwise_mul、elementwise_min、 elementwise_max、 elementwise_pow、 elementwise_mod

2022-02-13 12:15 UTC, jiangjiajun requested changes

2022-02-13 12:15 UTC, jiangjiajun commented on paddle2onnx/mapper/elementwise.cc
> +  if (op.type() == "elementwise_min" || op.type() == "elementwise_max") {
在写的时候，如若发现原python版本的OP存在问题的话，也一并提一下。我刚看了下原Python代码中的elementwise，对于min和max在opset 7下的提示不对
```
        if node.type in ["elementwise_min", "elementwise_max"]:
            assert False, "when opset version < 8, the shape and dtype of {} op must be same".format(
                node.type)
```

2022-02-13 12:15 UTC, jiangjiajun commented on paddle2onnx/mapper/elementwise.cc
> +  if (op.type() == "elementwise_min" || op.type() == "elementwise_max") {
https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/paddle2onnx/op_mapper/math.py#L309

2022-02-13 12:15 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/reshape2.cc
> +int32_t Reshape2Mapper::GetMinOpset(bool verbose) {
这里的代码逻辑加注释说明下，光看代码太绕

2022-02-13 12:15 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/reshape2.cc
> +      shape_name = "Shape";
进入到else后，说明is_shapetensor即为True，则不存在tensor_info.size() == 0的情况

2022-02-13 12:15 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/reshape2.cc
> +    if (tensor_info.size() == 0) {
同上，当`is_shape`为true时，则不会存在tensor_info.size()为0的情况，参考定义[PaddleParser::OpHasInput()](https://github.com/PaddlePaddle/Paddle2ONNX/blob/cpp/paddle2onnx/parser/parser.cc#L253)

2022-02-13 12:15 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/reshape2.cc
> +  return 7;
这里的代码逻辑加注释说明下，光看代码有点迷

这里看完后，没明白会在什么场景下返回-1，是否是直接返回7？

2022-02-13 12:15 UTC, jiangjiajun commented on paddle2onnx/mapper/elementwise.cc
> +            ->output(0);
`MakeConstant` 改为新的helper函数`Constant`
此处改为
```
std::string broadcast_shape_node = helper->Constant(GetOnnxDtype(P2ODataType::INT64), broadcast_shape);
```

2022-02-13 12:15 UTC, jiangjiajun commented on paddle2onnx/mapper/elementwise.cc
> +      helper->MakeConstant(GetOnnxDtype(dtype), val_0)->output(0);
`MakeContant` -> `Constant`

2022-02-13 12:15 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/reshape2.cc
> +        helper->MakeConstant(GetOnnxDtype(P2ODataType::INT64), shape);
`MakeConstant` -> `Constant`

2022-02-13 12:15 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/reshape2.cc
> +    if (tensor_info.size() > 1) {
同上，在已知 `OpHasInput`已经包含`tensor_info.size() > 0`的前提示，代码可以写得更简洁

2022-02-13 12:15 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/squeeze2.cc
> +std::vector<int64_t> Squeeze2Mapper::comput_axes() {
函数改为`ComputeAxes`

此外在命名时可根据需求对英文单词进行缩写，但要考虑要实际可读性。 不建议`compute`缩写为`comput`，如若是在实现过程中从Python版本迁移过来，则同时也为Python代码提交下修改，解决一些这类实现命名的问题

2022-02-13 12:15 UTC, jiangjiajun commented on paddle2onnx/parser/parser.cc
> +    if (op.attrs(i).name() == name && GetOpAttrType(op, name) != "NOTFOUND") {
这里添加NOTFOUND的检查是为了处理什么情况，可在代码注释中也标明，便于后期代码的可读性和可维护性

2022-02-14 02:41 UTC, yeliang2258 commented on paddle2onnx/parser/parser.cc
> +    if (op.attrs(i).name() == name && GetOpAttrType(op, name) != "NOTFOUND") {
done

2022-02-14 02:41 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/squeeze2.cc
> +std::vector<int64_t> Squeeze2Mapper::comput_axes() {
done

2022-02-14 02:41 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/reshape2.cc
> +    if (tensor_info.size() > 1) {
done，这里是大于1个输入

2022-02-14 02:41 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/reshape2.cc
> +        helper->MakeConstant(GetOnnxDtype(P2ODataType::INT64), shape);
done

2022-02-14 02:41 UTC, yeliang2258 commented on paddle2onnx/mapper/elementwise.cc
> +      helper->MakeConstant(GetOnnxDtype(dtype), val_0)->output(0);
done

2022-02-14 02:41 UTC, yeliang2258 commented on paddle2onnx/mapper/elementwise.cc
> +            ->output(0);
done

2022-02-14 02:41 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/reshape2.cc
> +  return 7;
当输入中没有ShapeTensor和Shape，shape也不在属性中的时候返回-1，已经增加了提示.

2022-02-14 02:41 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/reshape2.cc
> +    if (tensor_info.size() == 0) {
done

2022-02-14 02:41 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/reshape2.cc
> +      shape_name = "Shape";
done

2022-02-14 02:41 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/reshape2.cc
> +int32_t Reshape2Mapper::GetMinOpset(bool verbose) {
已经精简了逻辑，增加了提示。

2022-02-14 02:41 UTC, yeliang2258 commented on paddle2onnx/mapper/elementwise.cc
> +  if (op.type() == "elementwise_min" || op.type() == "elementwise_max") {
done

2022-02-14 02:55 UTC, jiangjiajun requested changes

2022-02-14 02:55 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/reshape2.cc
> +  return 7;
错误提示仅在verbose为True下才输出

然后代码逻辑可以写得更直观一些，改成
```
bool has_shape_tensor_input = parser_->OpHasInput(block_idx_, op_idx_, "ShapeTensor");
bool has_shape_input = parser_->OpHasInput(block_idx_, op_idx_,  "Shape");
auto op = parser_->GetOpDesc(block_idx_, op_idx_);
bool has_shape_attr = parser_->OpHasAttr(op, "shape");
if (!has_shape_input && !has_shape_input and !has_shape_attr) {
  if (verbose) {
    std::cerr << "Can not find shape as input or attribute in op " << op.type() << "." << std::endl;
  }
  return -1;
}
return 7;
```

2022-02-14 02:55 UTC, jiangjiajun commented on paddle2onnx/parser/parser.cc
> +    if (op.attrs(i).name() == name && GetOpAttrType(op, name) != "NOTFOUND") {
现在是在什么情况下遇见了需要用到了NOTFOUND的情况，这种情况是Paddle模型允许的吗？

2022-02-14 03:32 UTC, yeliang2258 commented on paddle2onnx/parser/parser.cc
> +    if (op.attrs(i).name() == name && GetOpAttrType(op, name) != "NOTFOUND") {
模型运行，有这个属性，但是里面没数值。

2022-02-14 03:32 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/reshape2.cc
> +  return 7;
done

2022-02-14 03:38 UTC, yeliang2258 commented on paddle2onnx/parser/parser.cc
> +    if (op.attrs(i).name() == name && GetOpAttrType(op, name) != "NOTFOUND") {
squeeze2允许这种情况。

2022-02-14 03:48 UTC, jiangjiajun approved these changes

2022-02-14 03:48 UTC, merged