add some ops
PaddlePaddle/Paddle2ONNX pull request #550
Opened 2022-02-15 06:32 UTC by yeliang2258

1. add scale batch_norm assign_value unsqueeze2 depthwise_conv2d softmax

2022-02-15 12:42 UTC, jiangjiajun requested changes

2022-02-15 12:42 UTC, jiangjiajun commented on paddle2onnx/mapper/activation.cc
> +  int64_t axis;
这里的获取移到Init里面吧，统一Attribute都在类的私有变量里声明

2022-02-15 12:42 UTC, jiangjiajun commented on paddle2onnx/mapper/activation.cc
> +    }
auto perm = data_helper.h::Arange(0, output_info[0].Rank())

2022-02-15 12:42 UTC, jiangjiajun commented on paddle2onnx/mapper/activation.h
> +};
axis变量声明在这

2022-02-15 12:42 UTC, jiangjiajun commented on paddle2onnx/mapper/exporter.cc
> +      valid_op_num += 1;
为什么加这个逻辑？

2022-02-15 12:42 UTC, jiangjiajun commented on paddle2onnx/mapper/nn/batch_norm.cc
> +  if (export_opset_version_ < 9) {
opset_version统一从helper中获取吧，增加`ONNXHelper::GetOpserVersion()`接口
后面不再维护多个opset_version字段

2022-02-15 12:42 UTC, jiangjiajun commented on paddle2onnx/mapper/nn/dropout.cc
> +                << " is not support in op " << op.type() << "." << std::endl;
已经知道是dropout了，为何还需要再获取op.type

2022-02-15 12:42 UTC, jiangjiajun commented on paddle2onnx/mapper/nn/scale.cc
> +        input_info[0].dtype == P2ODataType::INT16) {
这里是否是`if input_info[0].dtype != P2ODataType::FP32`  或者`input_info[0].dtype != FP32 && input_info[0].dtype != FP64`

2022-02-15 12:42 UTC, jiangjiajun commented on paddle2onnx/mapper/nn/scale.cc
> +    std::string output;
看了下整体逻辑，output的作用是用来判断最终是否需要将结果cast回去
改成更直接的flag吧，逻辑也可以精简些
```
    bool is_int_input = false;
    std::string float_input_name = input_info[0].name;
    if (input_info[0].dtype == P2ODataType::INT64 ||
        input_info[0].dtype == P2ODataType::INT32 ||
        input_info[0].dtype == P2ODataType::INT16) {
      is_int_input = true;
      std::cerr << " Int type input may bring calculation diff in op "
                << op.type() << "." << std::endl;
      cast_node = helper->AutoCast(input_info[0].name, input_info[0].dtype,
                                   P2ODataType::FP32);
      float_input_name = cast_node->output(0);
    } 
```

2022-02-15 12:42 UTC, jiangjiajun commented on paddle2onnx/mapper/nn/scale.cc
> +      std::vector<TensorInfo> scaletensor_info =
变量命名使用下划线连接

2022-02-15 12:42 UTC, jiangjiajun commented on paddle2onnx/mapper/nn/scale.cc
> +      scale_node = helper->Constant(GetOnnxDtype(data_type), scale_vector);
这里可直接写成`scale_node = helper->Constant({1}, GetOnnxDtype(input_info[0].dtype), scale_);`

2022-02-15 12:42 UTC, jiangjiajun commented on paddle2onnx/mapper/nn/scale.cc
> +        helper->Constant(GetOnnxDtype(data_type), bias_vector);
同上

2022-02-15 12:42 UTC, jiangjiajun commented on paddle2onnx/mapper/nn/scale.cc
>      if (bias_after_scale_) {
代码中尽量减少这种未初始化的变量使用，在下面的代码逻辑中，有一个分支并没对这个变量进行操作，那这个变量的处理就完全取决于开发者对逻辑的信息了

2022-02-15 12:42 UTC, jiangjiajun commented on paddle2onnx/mapper/nn/scale.cc
> +                    ->output(0);
可以将下面的Cast逻辑移到这个else里面来，移除上面的node2。 整体代码行数还更精简

2022-02-15 12:42 UTC, jiangjiajun commented on paddle2onnx/mapper/onnx_helper.cc
> +    const std::shared_ptr<ONNX_NAMESPACE::NodeProto>& node) {
这个函数的作用是什么

2022-02-15 12:42 UTC, jiangjiajun commented on paddle2onnx/mapper/onnx_helper.cc
> +    if (i > max_index) max_index = i;
我们的代码中，所有的条件分支都包在花括号内，统一风格

2022-02-15 12:42 UTC, jiangjiajun commented on paddle2onnx/mapper/onnx_helper.cc
> +  for (auto i = 0; i < input_info.size(); i++) {
for循环也同样改成++i，统一风格吧

2022-02-16 07:51 UTC, yeliang2258 commented on paddle2onnx/mapper/activation.cc
> +  int64_t axis;
done

2022-02-16 07:51 UTC, yeliang2258 commented on paddle2onnx/mapper/activation.cc
> +    }
done

2022-02-16 07:52 UTC, yeliang2258 commented on paddle2onnx/mapper/activation.h
> +};
done

2022-02-16 07:52 UTC, yeliang2258 commented on paddle2onnx/mapper/exporter.cc
> +      valid_op_num += 1;
因为有可能有输入，有输出，但是没有OP

2022-02-16 07:52 UTC, yeliang2258 commented on paddle2onnx/mapper/nn/batch_norm.cc
> +  if (export_opset_version_ < 9) {
done

2022-02-16 07:52 UTC, yeliang2258 commented on paddle2onnx/mapper/nn/dropout.cc
> +                << " is not support in op " << op.type() << "." << std::endl;
done

2022-02-16 07:52 UTC, yeliang2258 commented on paddle2onnx/mapper/nn/scale.cc
> +        input_info[0].dtype == P2ODataType::INT16) {
这是是如果为int类型则转换为float进行计算，pf32和pf64则按照原来的类型进行计算

2022-02-16 07:52 UTC, yeliang2258 commented on paddle2onnx/mapper/nn/scale.cc
> +    std::string output;
done

2022-02-16 07:52 UTC, yeliang2258 commented on paddle2onnx/mapper/nn/scale.cc
> +      std::vector<TensorInfo> scaletensor_info =
done

2022-02-16 07:52 UTC, yeliang2258 commented on paddle2onnx/mapper/nn/scale.cc
> +      scale_node = helper->Constant(GetOnnxDtype(data_type), scale_vector);
done

2022-02-16 07:52 UTC, yeliang2258 commented on paddle2onnx/mapper/nn/scale.cc
> +        helper->Constant(GetOnnxDtype(data_type), bias_vector);
done

2022-02-16 07:52 UTC, yeliang2258 commented on paddle2onnx/mapper/nn/scale.cc
>      if (bias_after_scale_) {
done

2022-02-16 07:52 UTC, yeliang2258 commented on paddle2onnx/mapper/nn/scale.cc
> +                    ->output(0);
done

2022-02-16 07:52 UTC, yeliang2258 commented on paddle2onnx/mapper/onnx_helper.cc
> +    const std::shared_ptr<ONNX_NAMESPACE::NodeProto>& node) {
已经修改，为nodes增加一个weight构造的const结点

2022-02-16 07:52 UTC, yeliang2258 commented on paddle2onnx/mapper/onnx_helper.cc
> +    if (i > max_index) max_index = i;
done

2022-02-16 07:52 UTC, yeliang2258 commented on paddle2onnx/mapper/onnx_helper.cc
> +  for (auto i = 0; i < input_info.size(); i++) {
done

2022-02-17 08:35 UTC, jiangjiajun commented
这个PR可以Close了吗？

2022-02-17 08:39 UTC, yeliang2258 commented
你不要管我这个PR，这个我对照来看的

2022-02-24 02:32 UTC, closed without merging