add upsqueeze2 and its tests
PaddlePaddle/Paddle2ONNX pull request #560
Opened 2022-02-18 07:18 UTC by yeliang2258

1. Add unsqueeze2

2022-02-18 08:06 UTC, jiangjiajun requested changes

2022-02-18 08:06 UTC, jiangjiajun commented on paddle2onnx/mapper/onnx_helper.cc
> +  out_dtype = max_index;
out_dtype是写出值的话，也改成指针传入

2022-02-18 08:06 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/concat.cc
> +    value.get(axes);
同上，写入值改为使用指针传入，这里调用则是value.get(&axes)

2022-02-18 08:06 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/concat.cc
> +  helper->AutoCast(node->output(0), casted_dtype, output_info[0].dtype);
第74行代码的作用是？
如若是想让dtype与输出一致，在72行看到已经使用了output_info[0].name了，那在这个AutoCast中是否是创建了一个不会被用到的node

2022-02-18 08:06 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/split.cc
> +    //   AddAttribute(node, "split", sections);
注释的代码如不需要，删除

2022-02-18 08:06 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/split.cc
> +    //   AddAttribute(node, "axis", axis[0]);
同上

2022-02-18 08:06 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/split.cc
> +  if (has_attr) {
这里有个疑问点需要确认下，是否每个attr都需要来判断是否存在。 现在OP转换中，有些是直接获取，有些地方又额外再加入了HasAttr来判断，这是否是必要的。

如在Operator中定义了是可选的，用HasAttr来判断是合理的。 但如若是可选的，那感觉是额外引入了不必要的逻辑

2022-02-18 08:06 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/split.cc
> +      for (auto i : sections) sum_val += i;
所有的花括号我们统一风格不省略

2022-02-18 08:06 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/split.cc
> +      if (input_info[0].shape[i] == -1) input_index.push_back(i);
所有的花括号我们统一风格不省略

2022-02-18 08:06 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/split.h
> +  std::vector<int64_t> GetAxes();
除构造、和GetMinOpset， OpsetX函数外，其余的放在private里面吧

2022-02-18 08:06 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/unsqueeze2.cc
> +  if (has_attr) return 7;
风格同上

2022-02-18 10:44 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/split.cc
> +  if (has_attr) {
因为有一些OP是可选的，有可能有，也可能没有，这个视OP而定

2022-02-18 10:44 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/split.cc
> +      for (auto i : sections) sum_val += i;
done

2022-02-18 10:45 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/split.cc
> +      if (input_info[0].shape[i] == -1) input_index.push_back(i);
done

2022-02-18 10:45 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/split.h
> +  std::vector<int64_t> GetAxes();
done

2022-02-18 10:45 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/unsqueeze2.cc
> +  if (has_attr) return 7;
done

2022-02-18 10:45 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/split.cc
> +    //   AddAttribute(node, "axis", axis[0]);
done

2022-02-18 10:45 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/split.cc
> +    //   AddAttribute(node, "split", sections);
done

2022-02-18 10:45 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/concat.cc
> +  helper->AutoCast(node->output(0), casted_dtype, output_info[0].dtype);
已经删除，打错了

2022-02-18 10:45 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/concat.cc
> +    value.get(axes);
done

2022-02-18 10:45 UTC, yeliang2258 commented on paddle2onnx/mapper/onnx_helper.cc
> +  out_dtype = max_index;
done

2022-02-18 12:21 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/split.cc
> +  if (has_attr) {
但这里你在写的时候有注意哪些是可选的吗？我看了下这个OP的定义， section看起来是一个一定有的， 实际上目前还没发现哪个attr是会出现不存的情况，只有input才会出现

2022-02-21 02:20 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/split.cc
> +  if (has_attr) {
sections这个字段会一直存在，但是里面不一定有数据，如果直接取值，会报如下错误：
![image](https://user-images.githubusercontent.com/30516196/154878511-fafcf38c-effa-432d-8959-572a892dd5a6.png)

2022-02-21 02:31 UTC, jiangjiajun requested changes

2022-02-21 02:31 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/split.cc
> +  for (auto i : output_info) output_names.push_back(i.name);
这里风格统一用花括号

2022-02-21 02:31 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/split.cc
> +  if (has_attr) {
那是否是应该使用判断是否有值的那个判断，而不是HasAttr? 我看这个应该不会被HasAttr判断给拦截下来

2022-02-21 02:31 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/split.cc
> +    }
上面这段代码的逻辑是用于做什么的呢？添加下注释说明下

2022-02-21 02:39 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/split.cc
> +    }
HasAttr我已经修改为有这个attr并且有值才返回true

2022-02-21 02:40 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/split.cc
> +  for (auto i : output_info) output_names.push_back(i.name);
done

2022-02-21 07:04 UTC, jiangjiajun requested changes

2022-02-21 07:04 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/split.cc
> +    }
这里的判断在动转静时已经判断，无需再加判断

2022-02-21 07:04 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/unsqueeze2.cc
> +  if (!found_value) {
在高版本的opset中，支持axis以tensor方式输入

2022-02-21 07:04 UTC, jiangjiajun commented on paddle2onnx/parser/parser.cc
> +  return {};
都找不到属于正常情况吗，是否是应该直接Assert掉

2022-02-21 07:56 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/unsqueeze2.cc
> +  if (!found_value) {
done

2022-02-21 07:56 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/split.cc
> +    }
done

2022-02-21 07:56 UTC, yeliang2258 commented on paddle2onnx/parser/parser.cc
> +  return {};
done，加入assret

2022-02-21 09:07 UTC, jiangjiajun approved these changes

2022-02-21 09:07 UTC, merged