Add pool and models test
PaddlePaddle/Paddle2ONNX pull request #566
Opened 2022-02-21 12:57 UTC by yeliang2258

1. Add pool and its tests
2. Add model convert and diff check script
```
1. mkdir Models( under test folder )
2. bash test_models.sh 
```

2022-02-23 01:18 UTC, jiangjiajun requested changes

2022-02-23 01:18 UTC, jiangjiajun commented on paddle2onnx/mapper/onnx_helper.cc
> +void AddAttribute(std::shared_ptr<ONNX_NAMESPACE::NodeProto> node,
ONNX的定义中，没有为bool的Attribute，在这个函数看到也是把bool转成int来赋值，这步改成调用的时候直接调用`AddAttribute(node, int)`

2022-02-23 02:21 UTC, yeliang2258 commented on paddle2onnx/mapper/onnx_helper.cc
> +void AddAttribute(std::shared_ptr<ONNX_NAMESPACE::NodeProto> node,
done

2022-02-23 12:48 UTC, jiangjiajun requested changes

2022-02-23 12:48 UTC, jiangjiajun commented on tests/test_auto_scan_adaptiveavgpool_ops.py
> +        dtype = draw(st.sampled_from(["float32"]))
paddle的dtype支持范围很广，与paddle对齐

2022-02-23 12:48 UTC, jiangjiajun commented on paddle2onnx/mapper/onnx_helper.cc
> +void AddAttribute(std::shared_ptr<ONNX_NAMESPACE::NodeProto> node,
其实我的意思是ONNX没有bool的attribute，在OP转换时，直接就调用AddAttribute(node, int)这个函数即可，便如AddAttribute(node, static_cast<int>(bool_value)), 这样大家在调用这个接口的时候，不会产生ONNX原生支持bool dtype的错觉

2022-02-23 12:48 UTC, jiangjiajun commented on tests/convert_and_check.py
> +#   Copyright (c) 2022 PaddlePaddle Authors. All Rights Reserved.
这个改名为convert_and_check_cv_backbones.py吧， 这个后面应该只是模型测试中的一个part

2022-02-23 12:48 UTC, jiangjiajun commented on tests/test_auto_scan_adaptiveavgpool_ops.py
> +        dtype = draw(st.sampled_from(["float32"]))
其它几个同理

2022-02-23 13:15 UTC, yeliang2258 commented on paddle2onnx/mapper/onnx_helper.cc
> +void AddAttribute(std::shared_ptr<ONNX_NAMESPACE::NodeProto> node,
done

2022-02-23 13:45 UTC, yeliang2258 commented on tests/test_auto_scan_adaptiveavgpool_ops.py
> +        dtype = draw(st.sampled_from(["float32"]))
done

2022-02-23 13:49 UTC, yeliang2258 commented on tests/convert_and_check.py
> +#   Copyright (c) 2022 PaddlePaddle Authors. All Rights Reserved.
done

2022-02-24 02:29 UTC, jiangjiajun approved these changes

2022-02-24 02:29 UTC, merged