fix pool and add avgpool test
PaddlePaddle/Paddle2ONNX pull request #573
Opened 2022-02-23 10:26 UTC by yeliang2258

1. Fix the judgment of static shape in the pool.
2. add avgpool test

2022-02-23 12:48 UTC, jiangjiajun requested changes

2022-02-23 12:48 UTC, jiangjiajun commented on tests/test_auto_scan_avgpool.py
> +        dtype = draw(st.sampled_from(["float32"]))
这个也对应C++的改一下吧

2022-02-23 14:06 UTC, yeliang2258 commented on tests/test_auto_scan_avgpool.py
> +        dtype = draw(st.sampled_from(["float32"]))
done

2022-02-24 02:32 UTC, jiangjiajun approved these changes

2022-02-24 02:32 UTC, merged