Add 3 OPs and its test
PaddlePaddle/Paddle2ONNX pull request #583
Opened 2022-02-28 13:06 UTC by yeliang2258

1. Add cast

2022-02-28 13:56 UTC, jiangjiajun requested changes

2022-02-28 13:56 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/equal.cc
> +void EqualMapper::Opset7(OnnxHelper* helper) {
注意下equal这个OP里面的axis参数，需要assert掉

2022-02-28 13:56 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/equal.cc
> +void EqualMapper::Opset7(OnnxHelper* helper) {
在之前，用户是可以通过api来配置axis参数的，现在虽然屏蔽了这个参数，但是在我们代码里还是assert掉，避免出错

2022-02-28 13:56 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/logical_not.cc
> +  helper->MakeNode("Not", {input_info[0].name}, {output_info[0].name});
同上，看下有没有axis参数

2022-03-01 06:27 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/logical_not.cc
> +  helper->MakeNode("Not", {input_info[0].name}, {output_info[0].name});
这个没有axis

2022-03-01 06:29 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/equal.cc
> +void EqualMapper::Opset7(OnnxHelper* helper) {
done

2022-03-01 07:00 UTC, jiangjiajun approved these changes

2022-03-01 07:18 UTC, merged