Add 4 ops
PaddlePaddle/Paddle2ONNX pull request #591
Opened 2022-03-02 06:56 UTC by yeliang2258

1. Add fill_any_like and fill_zero_like

2022-03-03 05:31 UTC, jiangjiajun requested changes

2022-03-03 05:31 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/fill_like.cc
> +  }
为什么dtype不是默认获取，而是在这里判断是否存在

2022-03-03 05:31 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/fill_like.cc
> +  helper->ConstOfShape(shape_node->output(0), output_info[0].name, dims,
不使用这个dtype，因为它不准， 改成使用GetOnnxDtype(output_jnfo[0].dtype)。

事实上在开发时，能够使用output_info[0].dtype的地方，就尽量用这个，此前生辉已经遇到不少这样的问题了。参照下面这个case

<img width="558" alt="image" src="https://user-images.githubusercontent.com/19339784/156502389-73b97732-6ba9-42de-92f8-55231efc35f5.png">

2022-03-03 05:31 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/fill_like.cc
> +  }
这里在开发时，你是根据什么因素来决定的

2022-03-03 07:02 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/fill_like.cc
> +  helper->ConstOfShape(shape_node->output(0), output_info[0].name, dims,
done

2022-03-03 07:02 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/fill_like.cc
> +  }
因为有一些OP确实没有dtype这个属性

2022-03-03 07:06 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/fill_like.cc
> +  helper->ConstOfShape(shape_node->output(0), output_info[0].name, dims,
上图如果指定了dtype的话，5就是表示float

2022-03-03 09:39 UTC, jiangjiajun requested changes

2022-03-03 09:39 UTC, jiangjiajun commented on paddle2onnx/cpp2py_export.cc
> +  m.def("get_all_registered_ops", []() {
增加这个是用于干啥的，没看到当前哪里用到了

2022-03-03 09:39 UTC, jiangjiajun commented on paddle2onnx/mapper/nn/layer_norm.cc
> +      helper->MakeConstant({1}, GetOnnxDtype(input_info[0].dtype), epsilon_)
MakeConstant，全部改为调用`helper->Constant`吧

2022-03-03 09:39 UTC, jiangjiajun commented on paddle2onnx/mapper/onnx_helper.h
> +    ONNX_NAMESPACE::TensorProto_DataType dtype, T value) {
这个函数，与函数
```
  template <typename T>
  std::string OnnxHelper::Constant(const std::string& output,
                       const std::vector<int64_t>& shape,
                       ONNX_NAMESPACE::TensorProto_DataType dtype, T value);
```
的差别是什么

2022-03-03 09:39 UTC, jiangjiajun commented on paddle2onnx/mapper/register_mapper.h
> +    std::ofstream outfile("RegisteredOPs.txt");
这里看起来很trick, 在一个绝对路径下写了一个文件，怎么确定这个目录有没有写的权限

2022-03-03 09:39 UTC, jiangjiajun commented on tests/test_auto_scan_fill_like.py
> +        dtype = draw(st.sampled_from(["int64", "float32", "float64"]))
dtype与paddle api一致，之后的PR，可先看下paddle的api再设置这个参数

2022-03-03 09:39 UTC, jiangjiajun commented on tests/test_auto_scan_layer_norm.py
> +        dtype = draw(st.sampled_from(["float32"]))
同上

2022-03-03 13:44 UTC, yeliang2258 commented on paddle2onnx/cpp2py_export.cc
> +  m.def("get_all_registered_ops", []() {
这个是我看每次我们统计OP的时候要一个个去数，我就写了这个函数，要统计OP的时候可以一键统计，这个是我们开发人员自己用的，用户可以不知道。

2022-03-03 13:48 UTC, yeliang2258 commented on paddle2onnx/mapper/onnx_helper.h
> +    ONNX_NAMESPACE::TensorProto_DataType dtype, T value) {
这个OP的输入是需要构成的const的shape，相当于一个const加上一个reshape

2022-03-03 13:49 UTC, yeliang2258 commented on paddle2onnx/mapper/register_mapper.h
> +    std::ofstream outfile("RegisteredOPs.txt");
这个是我们自己使用的，统计OP用，不面对用户

2022-03-03 14:07 UTC, jiangjiajun commented on paddle2onnx/mapper/register_mapper.h
> +    std::ofstream outfile("RegisteredOPs.txt");
自己写的也要保持可用的状态，建议把这个路径改为传入，而非写死的方式

2022-03-03 14:10 UTC, jiangjiajun requested changes

2022-03-03 14:10 UTC, jiangjiajun commented on paddle2onnx/mapper/onnx_helper.h
> +  }
onnx的OP定义里，要求这个tensor需要是一个one-element tensor， 为什么在这里却可以配置一个额外的shape呢？

2022-03-03 14:13 UTC, jiangjiajun commented on paddle2onnx/mapper/register_mapper.h
> +    std::ofstream outfile("RegisteredOPs.txt");
另外如果是内部使用，注释也说明下为什么写这个接口，用的场景是什么。 是一个可用的接口，只不过是“对内”（我理解也就是面对开发者），既然做开源，也还是需要注意代码和接口的规范性

2022-03-03 14:16 UTC, jiangjiajun commented on paddle2onnx/mapper/onnx_helper.h
> +  }
https://github.com/onnx/onnx/blob/main/docs/Operators.md#constantofshape

2022-03-04 03:56 UTC, yeliang2258 commented on paddle2onnx/mapper/register_mapper.h
> +    std::ofstream outfile("RegisteredOPs.txt");
done

2022-03-04 04:19 UTC, yeliang2258 commented on paddle2onnx/mapper/onnx_helper.h
> +  }
shape输入删除了

2022-03-04 05:00 UTC, yeliang2258 commented on tests/test_auto_scan_fill_like.py
> +        dtype = draw(st.sampled_from(["int64", "float32", "float64"]))
done

2022-03-04 05:00 UTC, yeliang2258 commented on tests/test_auto_scan_layer_norm.py
> +        dtype = draw(st.sampled_from(["float32"]))
done

2022-03-04 05:00 UTC, yeliang2258 commented on paddle2onnx/mapper/nn/layer_norm.cc
> +      helper->MakeConstant({1}, GetOnnxDtype(input_info[0].dtype), epsilon_)
done

2022-03-06 06:01 UTC, jiangjiajun requested changes
其它都没问题了，PR时就改这个register_mapper.h即可

2022-03-06 06:01 UTC, jiangjiajun commented on paddle2onnx/mapper/register_mapper.h
> +    std::ofstream outfile(file_path);
加一个判断，如若file_path没能成功读写，给一个错误提示

2022-03-06 15:35 UTC, merged

2022-03-07 03:32 UTC, yeliang2258 commented on paddle2onnx/mapper/register_mapper.h
> +    std::ofstream outfile(file_path);
Related: https://github.com/PaddlePaddle/Paddle2ONNX/pull/608