Add lookup_table
PaddlePaddle/Paddle2ONNX pull request #600
Opened 2022-03-03 07:15 UTC by yeliang2258

1. Add lookup_table

2022-03-06 06:09 UTC, jiangjiajun requested changes

2022-03-06 06:09 UTC, jiangjiajun commented on paddle2onnx/mapper/onnx_helper.h
> +    ONNX_NAMESPACE::TensorProto_DataType dtype, std::vector<T>& value) {
添加到helper->constant里面，OP转换里，都统一只调用helper-Constant这个接口，不引入新的接口

2022-03-07 07:09 UTC, yeliang2258 commented on paddle2onnx/mapper/onnx_helper.h
> +    ONNX_NAMESPACE::TensorProto_DataType dtype, std::vector<T>& value) {
done

2022-03-07 09:56 UTC, jiangjiajun approved these changes

2022-03-07 13:42 UTC, merged