New quantize dev
PaddlePaddle/Paddle2ONNX pull request #651
Opened 2022-03-25 09:59 UTC by yeliang2258

Support PaddleSlim quantize model convert to ONNX model

2022-04-13 09:04 UTC, yeliang2258 commented on paddle2onnx/convert.py
> +    max_range_file_path = "max_range.txt"
加路径

2022-04-13 09:04 UTC, yeliang2258 commented on paddle2onnx/graph/graph_helper.py
> +            weight_input = pre_node.input('Filter', 0)
使用op.type来判断

2022-04-13 09:04 UTC, yeliang2258 commented on paddle2onnx/graph/graph_helper.py
> +            update_param, weight = mapper_helper.get_param_from_paddle_graph(
第二个输入是tensor

2022-04-13 09:04 UTC, yeliang2258 commented on paddle2onnx/graph/graph_helper.py
> +            if key is None:
if key is None or len(key)==0:

2022-04-13 09:04 UTC, yeliang2258 commented on paddle2onnx/graph/graph_helper.py
> +                    quant_axis = 0
quant_axis = -1

2022-04-13 09:04 UTC, yeliang2258 commented on paddle2onnx/graph/graph_helper.py
> +                input_shape = pre_node.input_shape('Y', 0)
delete

2022-04-13 09:04 UTC, yeliang2258 commented on paddle2onnx/graph/graph_helper.py
> +            if graph.is_graph_output(node.output('Out', 0)):
删除

2022-04-13 09:04 UTC, yeliang2258 commented on paddle2onnx/op_mapper/quantize.py
> +        else:
assert

2022-04-13 09:39 UTC, yeliang2258 commented on paddle2onnx/convert.py
> +    max_range_file_path = "max_range.txt"
Done

2022-04-13 09:40 UTC, yeliang2258 commented on paddle2onnx/graph/graph_helper.py
> +            weight_input = pre_node.input('Filter', 0)
done

2022-04-13 09:40 UTC, yeliang2258 commented on paddle2onnx/graph/graph_helper.py
> +            update_param, weight = mapper_helper.get_param_from_paddle_graph(
Done

2022-04-13 13:19 UTC, yeliang2258 commented on paddle2onnx/convert.py
> +    max_range_file_path = "max_range.txt" if path is '' else path + "/max_range.txt"
os.path.join

2022-04-13 13:19 UTC, yeliang2258 commented on paddle2onnx/graph/onnx_graph.py
> +        if self.quantize_model_mode not in ["float"]:
if self.quantize_model_mode =! "float":

2022-04-13 13:19 UTC, yeliang2258 commented on paddle2onnx/graph/onnx_graph.py
> +    def replace_input_of_all_nodes(self, old_input_name, new_input_name):
delete

2022-04-13 13:19 UTC, yeliang2258 commented on paddle2onnx/graph/onnx_graph.py
> +        for layer_name, node in self.ctx.node_map.items():
重写

2022-04-13 13:19 UTC, yeliang2258 commented on paddle2onnx/op_mapper/mapper_helper.py
> +    '''
链接

2022-04-13 13:19 UTC, yeliang2258 commented on paddle2onnx/op_mapper/quantize.py
> +        if node.input('X', 0) not in graph.quantize_params_dict:
删除

2022-04-13 13:19 UTC, yeliang2258 commented on paddle2onnx/op_mapper/quantize.py
> +        if weight is not None:
注释

2022-04-13 13:19 UTC, yeliang2258 commented on paddle2onnx/op_mapper/quantize.py
> +        if weight is not None:
判断conv2d，不支持conv3d

2022-04-13 13:19 UTC, yeliang2258 commented on paddle2onnx/op_mapper/quantize.py
> +@op_mapper('moving_average_abs_max_scale')
原理

2022-04-13 13:19 UTC, yeliang2258 commented on paddle2onnx/passes/quantize_helper.py
> +        quantize_nodes = graph.quantize_params_dict[input_name]
quantize_parameters

2022-04-13 13:19 UTC, yeliang2258 commented on paddle2onnx/passes/quantize_helper.py
> +            if another_node.type in ["QuantizeLinear"]:
if another_node.type == ["QuantizeLinear"]:

2022-04-13 13:19 UTC, yeliang2258 commented on paddle2onnx/passes/quantize_helper.py
> +        for dequant_idx in range(idx + 1, len(node_map)):
直接下一个结点

2022-04-13 13:19 UTC, yeliang2258 commented on paddle2onnx/passes/quantize_helper.py
> +        if len(graph.input_name_to_nodes()[outputs]) > 1:
delete

2022-04-13 13:19 UTC, yeliang2258 commented on paddle2onnx/passes/quantize_helper.py
> +        for op_idx in range(idx + 2, len(node_map)):
简化

2022-04-13 13:19 UTC, yeliang2258 commented on paddle2onnx/passes/quantize_helper.py
> +        for dequant_idx in range(idx + 1, len(node_map)):
使用函数简化

2022-04-13 13:19 UTC, yeliang2258 commented on paddle2onnx/passes/quantize_helper.py
> +            if add_node.type not in ["Add"]:
if add_node.type not == "Add":

2022-04-13 13:19 UTC, yeliang2258 commented on paddle2onnx/passes/quantize_helper.py
> +        for bn_idx in range(idx + 1, len(node_map)):
简化

2022-04-13 13:19 UTC, yeliang2258 commented on paddle2onnx/passes/quantize_helper.py
> +            input_name_to_nodes = graph.input_name_to_nodes()
简化

2022-04-13 13:19 UTC, yeliang2258 commented on paddle2onnx/passes/quantize_helper.py
> +                continue
不是整个图的输出

2022-04-13 13:19 UTC, yeliang2258 commented on paddle2onnx/passes/quantize_helper.py
> +            if bias_node not in output_name_from_nodes:
删除

2022-04-13 13:19 UTC, yeliang2258 commented on paddle2onnx/passes/quantize_helper.py
> +                if bias_weight is None:
Reshape的第二个输入的判断

2022-04-13 13:19 UTC, yeliang2258 commented on paddle2onnx/passes/quantize_helper.py
> +        for bn_idx in range(idx + 1, len(node_map)):
简化

2022-04-13 13:19 UTC, yeliang2258 commented on paddle2onnx/passes/quantize_helper.py
> +            momentum = bn_node.attr("momentum")
删除

2022-04-13 13:19 UTC, yeliang2258 commented on paddle2onnx/passes/quantize_helper.py
> +                graph.quantize_params_dict[node.inputs[
删除

2022-04-13 13:19 UTC, yeliang2258 commented on paddle2onnx/passes/quantize_helper.py
> +        if len(graph.quantize_params_dict) == 0:
删除

2022-04-13 13:19 UTC, yeliang2258 commented on paddle2onnx/passes/quantize_helper.py
> +            else:
可以删除

2022-04-14 05:09 UTC, yeliang2258 commented on paddle2onnx/graph/graph_helper.py
> +                input_shape = pre_node.input_shape('Y', 0)
done

2022-04-14 05:17 UTC, yeliang2258 commented on paddle2onnx/convert.py
> +    max_range_file_path = "max_range.txt" if path is '' else path + "/max_range.txt"
Done

2022-04-14 06:54 UTC, yeliang2258 commented on paddle2onnx/passes/quantize_helper.py
> +            else:
因为constant op的存在，修改constant op的输出比较麻烦，暂时不删除

2022-04-14 07:28 UTC, yeliang2258 commented on paddle2onnx/graph/onnx_graph.py
> +        if self.quantize_model_mode not in ["float"]:
Done

2022-04-14 07:30 UTC, yeliang2258 commented on paddle2onnx/graph/onnx_graph.py
> +    def replace_input_of_all_nodes(self, old_input_name, new_input_name):
move to quantize_helper

2022-04-14 07:30 UTC, yeliang2258 commented on paddle2onnx/graph/onnx_graph.py
> +        for layer_name, node in self.ctx.node_map.items():
Done

2022-04-14 07:30 UTC, yeliang2258 commented on paddle2onnx/op_mapper/mapper_helper.py
> +    '''
deleted

2022-04-14 07:32 UTC, yeliang2258 commented on paddle2onnx/passes/quantize_helper.py
> +            if another_node.type in ["QuantizeLinear"]:
Done

2022-04-14 07:33 UTC, yeliang2258 commented on paddle2onnx/passes/quantize_helper.py
> +            if add_node.type not in ["Add"]:
Done

2022-04-14 08:38 UTC, yeliang2258 commented on paddle2onnx/op_mapper/quantize.py
> +        if node.input('X', 0) not in graph.quantize_params_dict:
Done

2022-04-14 08:42 UTC, yeliang2258 commented on paddle2onnx/op_mapper/quantize.py
> +        if weight is not None:
Done

2022-04-14 08:43 UTC, yeliang2258 commented on paddle2onnx/passes/quantize_helper.py
> +        quantize_nodes = graph.quantize_params_dict[input_name]
Done

2022-04-14 08:43 UTC, yeliang2258 commented on paddle2onnx/passes/quantize_helper.py
> +        for dequant_idx in range(idx + 1, len(node_map)):
Done

2022-04-14 09:17 UTC, yeliang2258 commented on paddle2onnx/op_mapper/quantize.py
> +@op_mapper('moving_average_abs_max_scale')
框架bug，已修

2022-04-26 02:43 UTC, jiangjiajun requested changes

2022-04-26 02:43 UTC, jiangjiajun commented on paddle2onnx/graph/onnx_graph.py
> +            if node.type.count("conv") or node.type.count("matmul"):
为什么需要是op为conv/matmul，且下一个OP的名字中包含dequantize或quantize_dequantize，才为static。 直接判断模型中的OP是否存在dequantize或quantize_dequantize，会有什么问题

2022-04-26 03:00 UTC, jiangjiajun requested changes

2022-04-26 03:00 UTC, jiangjiajun commented on paddle2onnx/graph/onnx_graph.py
> +            if node.type.count("conv") or node.type.count("matmul"):
为什么需要是op为conv/matmul，且下一个OP的名字中包含dequantize或quantize_dequantize，才为static。 直接判断模型中的OP是否存在dequantize或quantize_dequantize，会有什么问题

2024-05-22 03:44 UTC, closed without merging