Add unsqueeze helper
PaddlePaddle/Paddle2ONNX pull request #652
Opened 2022-03-28 07:51 UTC by yeliang2258

Add unsqueeze helper

2022-03-28 11:05 UTC, jiangjiajun requested changes

2022-03-28 11:05 UTC, jiangjiajun commented on paddle2onnx/passes/rename_node_pass.py
> +            name_mapping.clear()
这行可删除

2022-03-29 04:00 UTC, jiangjiajun requested changes

2022-03-29 04:00 UTC, jiangjiajun commented on paddle2onnx/passes/dumplicate_output_pass.py
> +            name_mapping.clear()
这行代码没必要

2022-03-29 07:04 UTC, yeliang2258 commented on paddle2onnx/passes/dumplicate_output_pass.py
> +            name_mapping.clear()
确实可以n的复杂度解决这个问题，已经更新了算法

2022-03-29 10:59 UTC, jiangjiajun requested changes

2022-03-29 10:59 UTC, jiangjiajun commented on paddle2onnx/passes/dumplicate_output_pass.py
> +                tensor_names.append(opt)
这里的tensor_names改为set()， 查找效率更高

2022-03-29 10:59 UTC, jiangjiajun commented on paddle2onnx/passes/dumplicate_output_pass.py
> +                while updated_name in renamer.keys():
这里直接写成while updated_name in renamer: 就行

2022-03-29 11:32 UTC, yeliang2258 commented on paddle2onnx/passes/dumplicate_output_pass.py
> +                while updated_name in renamer.keys():
Done

2022-03-29 11:32 UTC, yeliang2258 commented on paddle2onnx/passes/dumplicate_output_pass.py
> +                tensor_names.append(opt)
Done

2022-03-29 11:33 UTC, jiangjiajun approved these changes

2022-03-29 12:28 UTC, merged