Add 1 OPs convert
PaddlePaddle/Paddle2ONNX pull request #655
Opened 2022-03-29 12:28 UTC by yeliang2258

1. Add eye and its test

2022-03-30 03:39 UTC, jiangjiajun requested changes

2022-03-30 03:39 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +    def opset_9(cls, graph, node, **kw):
这里修改的原因是什么？

2022-03-30 03:39 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +            'EyeLike', inputs=[value_tensor], outputs=node.output('Out'))
最终输出的dtype需要与paddle一致

2022-03-30 07:27 UTC, yeliang2258 commented on paddle2onnx/op_mapper/tensor.py
> +    def opset_9(cls, graph, node, **kw):
改错位置了，改回来了

2022-03-30 07:27 UTC, yeliang2258 commented on paddle2onnx/op_mapper/tensor.py
> +            'EyeLike', inputs=[value_tensor], outputs=node.output('Out'))
Done

2022-03-30 07:31 UTC, jiangjiajun requested changes

2022-03-30 07:31 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +            outputs=node.output('Out'))
有几个attribute和输入，需要处理完
- 1. Attribute::allow_out_of_range
- 2. Attribute::dtype
- 3. Input::depth_tensor

2022-03-30 07:31 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +            eye_node = graph.make_node('EyeLike', inputs=[value_tensor])
`EyeLike`可以指定输出shape，无需`cast`

2022-03-30 07:35 UTC, jiangjiajun commented
PR标题此后如若OP不多，直接改为增加的OP名称，以便于代码PR的追溯

2022-03-30 07:50 UTC, yeliang2258 commented on paddle2onnx/op_mapper/tensor.py
> +            outputs=node.output('Out'))
Attribute::dtype我默认和output的保持一致，不需要处理。

2022-03-30 07:52 UTC, yeliang2258 commented on paddle2onnx/op_mapper/tensor.py
> +            eye_node = graph.make_node('EyeLike', inputs=[value_tensor])
和output dtype保持一致

2022-03-30 08:05 UTC, yeliang2258 commented on paddle2onnx/op_mapper/tensor.py
> +            outputs=node.output('Out'))
Input::depth_tensor：已新增支持

2022-03-30 08:59 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +            outputs=node.output('Out'))
> 1. Attribute::dtype我默认和output的保持一致，不需要处理。
> 2. Attribute::allow_out_of_range为False的时候Paddle报错，ONNX的one_hot也支持True，我认为不需要特殊处理

在Paddle2ONNX里面assert allow_out_of_range这个属性，后面这种不支持的情况，或者没有测到的情况，都需要加上assert和相应的提示信息

2022-03-30 09:05 UTC, jiangjiajun requested changes

2022-03-30 09:05 UTC, jiangjiajun commented on paddle2onnx/op_mapper/tensor.py
> +                    'Cast', inputs=[depth_tensor], to=out_dtype)
if条件外的depth_node设置为in_dtype类型，if条件内的depth_node设置为out_dtype类型，为什么会存在差异。

另外如若有必要cast，则直接将indices和depth_node都cast成int64

2022-03-30 09:34 UTC, jiangjiajun requested changes

2022-03-30 09:34 UTC, jiangjiajun commented on tests/test_auto_scan_one_hot_v2.py
> +        x = paddle.nn.functional.one_hot(inputs, num_classes)
添加num_classes为tensor的情况，即num_classes = paddle.to_tensor(num_classes) * 1

2022-03-30 09:48 UTC, yeliang2258 commented on paddle2onnx/op_mapper/tensor.py
> +                    'Cast', inputs=[depth_tensor], to=out_dtype)
判断条件有误，应该是：if depth_tensor_dtype != in_dtype_paddle

2022-03-30 09:48 UTC, yeliang2258 commented on paddle2onnx/op_mapper/tensor.py
> +            outputs=node.output('Out'))
done

2022-03-30 09:53 UTC, yeliang2258 commented on tests/test_auto_scan_one_hot_v2.py
> +        x = paddle.nn.functional.one_hot(inputs, num_classes)
Done

2022-03-31 02:21 UTC, jiangjiajun approved these changes

2022-03-31 02:30 UTC, merged