[PaddlePaddle Hackathon] 85 打通Paddle模型苹果CoreML的部署
PaddlePaddle/Paddle2ONNX pull request #662
Opened 2022-03-31 11:12 UTC by franva

### PR Types
Others

### PR Changes

Docs

### Describe

- Task: https://github.com/PaddlePaddle/Paddle2ONNX/issues/613

添加了一个教程: 关于如何将Paddle MobileNetV3模型转换到 苹果的CoreML格式, 并且展示了用最新的iOS编成语言 Swift以及UI框架SwiftUI来调用转换好的CoreML模型, 并且进行预测.

2022-04-01 02:32 UTC, jiangjiajun commented
GitHub上不适合提交太大的文件，请修改当前模型的存放方式。例如是否有必要提交转换后的模型，或者模型以网盘形式上传

2022-04-03 03:11 UTC, franva commented
> GitHub上不适合提交太大的文件，请修改当前模型的存放方式。例如是否有必要提交转换后的模型，或者模型以网盘形式上传

好的,  我已经把两个大文件去掉, 并且加如了 OneDrive share links.  请查收

2022-04-06 03:47 UTC, jiangjiajun requested changes

2022-04-06 03:47 UTC, jiangjiajun commented on hardwares/coreml/README.md
>  # Apple CoreML
鉴于先前测试过程中，出现的各种问题，在此README下补充说明具体的测试环境，包括使用的各种软件的版本，操作系统版本等信息

2022-04-06 12:33 UTC, franva commented on hardwares/coreml/README.md
>  # Apple CoreML
多谢, 已加入版本号,并且使用列表形式记录各个版本的tutorial所对应的各个工具的版本号.
请参见: Paddle2ONNX/hardwares/coreml/README.md

如需改动, 请告知我. 谢谢

2022-04-07 03:44 UTC, jiangjiajun approved these changes

2022-04-07 03:44 UTC, merged