Add mish and its test
PaddlePaddle/Paddle2ONNX pull request #663
Opened 2022-03-31 11:13 UTC by yeliang2258

1. Add mish and its test

2022-04-01 02:24 UTC, jiangjiajun requested changes

2022-04-01 02:24 UTC, jiangjiajun commented on paddle2onnx/op_mapper/activation.py
> +                'Mul', inputs=[inputs, tanh_node], outputs=node.output('Out'))
参考 https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic_opset9.py#L723

2022-04-01 02:30 UTC, yeliang2258 commented on paddle2onnx/op_mapper/activation.py
> +                'Mul', inputs=[inputs, tanh_node], outputs=node.output('Out'))
paddle的比torch的复杂

2022-04-01 02:30 UTC, yeliang2258 commented on paddle2onnx/op_mapper/activation.py
> +                'Mul', inputs=[inputs, tanh_node], outputs=node.output('Out'))
按照paddle的原理写的

2022-04-01 02:37 UTC, jiangjiajun commented on paddle2onnx/op_mapper/activation.py
> +                'Mul', inputs=[inputs, tanh_node], outputs=node.output('Out'))
差异是什么？
另外后面在PR中，如若有已知的差异或者问题的话，在PR描述中列出来吧

2022-04-01 02:39 UTC, yeliang2258 commented on paddle2onnx/op_mapper/activation.py
> +                'Mul', inputs=[inputs, tanh_node], outputs=node.output('Out'))
计算公式不一样：
paddle
![image](https://user-images.githubusercontent.com/30516196/161184420-cf429966-7dff-42c8-a4a7-7a4c55791449.png)
torch
![image](https://user-images.githubusercontent.com/30516196/161184510-0933d15a-4171-4515-b766-1fde6c184a4b.png)

2022-04-01 02:51 UTC, jiangjiajun commented on paddle2onnx/op_mapper/activation.py
> +                'Mul', inputs=[inputs, tanh_node], outputs=node.output('Out'))
torch的softplus和上面截图的softplus有差别么

2022-04-01 07:01 UTC, yeliang2258 commented on paddle2onnx/op_mapper/activation.py
> +                'Mul', inputs=[inputs, tanh_node], outputs=node.output('Out'))
Done

2022-04-01 07:16 UTC, jiangjiajun requested changes

2022-04-01 07:16 UTC, jiangjiajun commented on paddle2onnx/op_mapper/activation.py
>              dtype = paddle.float32
这个OP中是否有threshold的属性需要assert

2022-04-01 07:19 UTC, yeliang2258 commented on paddle2onnx/op_mapper/activation.py
>              dtype = paddle.float32
这个OP中确实是有这个属性![image](https://user-images.githubusercontent.com/30516196/161214633-b9c15caf-0e0c-48f7-8881-ee68e6e36894.png)

2022-04-01 07:25 UTC, jiangjiajun commented on paddle2onnx/op_mapper/activation.py
>              dtype = paddle.float32
那assert掉，只支持20.f吧

2022-04-01 07:45 UTC, jiangjiajun requested changes

2022-04-01 07:45 UTC, jiangjiajun commented on paddle2onnx/op_mapper/activation.py
> +        assert threshold == 20, "In mish OP, the threshold only supports 20, no other values are supported"
改成np.fabs(threshold - 20) < 1e-04

2022-04-01 08:51 UTC, yeliang2258 commented on paddle2onnx/op_mapper/activation.py
> +        assert threshold == 20, "In mish OP, the threshold only supports 20, no other values are supported"
Done

2022-04-02 02:07 UTC, jiangjiajun approved these changes

2022-04-02 02:07 UTC, merged