add pow op (C++)
PaddlePaddle/Paddle2ONNX pull request #676
Opened 2022-04-08 10:17 UTC by neonhuang

2022-04-08 11:48 UTC, jiangjiajun requested changes

2022-04-08 11:48 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/pow.cc
> +
如果可以支持7，这个函数可以直接不用定义，使用蕨类函数的即可

2022-04-08 11:48 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/pow.cc
> +   || input_info[0].dtype == P2ODataType::FP64) {
可以直接写成 `if (input_info[0].dtype != P2ODataType::FP32)`

2022-04-08 11:48 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/pow.cc
> +     helper_->AutoCast(node->output(0), {output_info[0].name}, P2ODataType::FP32,
这个代码是怎么编译过的呢，第一个参数和第二个参数都只能是std::string类型 https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/paddle2onnx/mapper/onnx_helper.h#L79

2022-04-12 08:41 UTC, neonhuang commented on paddle2onnx/mapper/tensor/pow.cc
> +     helper_->AutoCast(node->output(0), {output_info[0].name}, P2ODataType::FP32,
我参考了，https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/paddle2onnx/mapper/activation.cc#L157

2022-04-13 02:33 UTC, jiangjiajun approved these changes

2022-04-19 02:11 UTC, merged