add Argsort and dist  op(C++)
PaddlePaddle/Paddle2ONNX pull request #703
Opened 2022-04-21 03:55 UTC by neonhuang

1. argsort/ dist op
2. fix dist test case

2022-04-21 14:31 UTC, jiangjiajun commented
https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/tests/run.sh#L40 参照这里的conv，将C++版本OP的单测加入到CI
同时此前已经整理的通过单测的OP，也都相应加上来

2022-04-22 09:31 UTC, neonhuang commented
done

2022-04-22 09:31 UTC, neonhuang commented
> https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/tests/run.sh#L40 参照这里的conv，将C++版本OP的单测加入到CI 同时此前已经整理的通过单测的OP，也都相应加上来

done

2022-04-24 11:34 UTC, jiangjiajun requested changes

2022-04-24 11:34 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/argsort.cc
> +
26-27行改成使用 `helper_->Slice(shape, {0}, {0}, {1});` 直观上感觉Slice的支持会更广泛

2022-04-24 11:34 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/argsort.cc
> +  auto out_node = helper_->MakeNode("TopK", {x_info[0].name, dim_size}, {output_info[0].name, indices_info[0].name});
TOPK在opset7时，不支持两个输入

2022-04-24 11:34 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/argsort.h
> +  int32_t GetMinOpset(bool verbose) { return 11; }
当opset不为默认7时，分为两种情况，
- 1.部分情况为7，部分情况需要更高
- 2.全部情况都需要为更高的版本

其中对于1情况，需要给出理由，输出信息例如`Logger(verbose, 10) << "While xxxx xxx reson, " << RequireOpset(10) << std::endl;`

对于2情况，则直接`Logger(verbose, 10) << RequireOpset(10) << std::endl;`

2022-04-24 11:34 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/dist.cc
> +
上面这两行代码改成符合Google代码风格。 在提交commit前，先`sh commit-prepare.sh`， 这样commit时，会自动检查代码。当前你可以使用`cpplint xxx.cc`来检查代码

2022-04-24 11:34 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/dist.cc
> +    Logger(true, 9) << "While p is 0.0, "<< RequireOpset(9) << std::endl;
`Logger(true, 9) <<` 改成 `Logger(verbose, 9)`

`verbose`控制了全局的日志是否要输出

2022-04-24 11:34 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/dist.h
> +  int32_t GetMinOpset(bool verbose);
`GetMinOpset(bool verbose = false)`所有的OP在定义这个函数时，都要给verbose赋上默认的赋值false

2022-04-25 07:28 UTC, neonhuang commented on paddle2onnx/mapper/tensor/argsort.cc
> +
done

2022-04-25 07:47 UTC, neonhuang commented on paddle2onnx/mapper/tensor/dist.cc
> +    Logger(true, 9) << "While p is 0.0, "<< RequireOpset(9) << std::endl;
done

2022-04-25 07:48 UTC, neonhuang commented on paddle2onnx/mapper/tensor/dist.h
> +  int32_t GetMinOpset(bool verbose);
done

2022-04-25 08:05 UTC, neonhuang commented on paddle2onnx/mapper/tensor/dist.cc
> +
done

2022-04-25 09:34 UTC, neonhuang commented on paddle2onnx/mapper/tensor/argsort.cc
> +  auto out_node = helper_->MakeNode("TopK", {x_info[0].name, dim_size}, {output_info[0].name, indices_info[0].name});
done

2022-04-25 09:34 UTC, neonhuang commented on paddle2onnx/mapper/tensor/argsort.h
> +  int32_t GetMinOpset(bool verbose) { return 11; }
done

2022-04-25 11:22 UTC, jiangjiajun requested changes

2022-04-25 11:22 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/argsort.cc
> +        << "While descending=False only support opset version>=11., "
改成Logger(verbose, 11) << "While descending=False,  " << RequireOpset(11) << std::endl;

因为`RequireOpset(11)`返回的字符串就是`requires opset version >= 11`

2022-04-25 11:22 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/argsort.cc
> +  auto out_node = helper_->MakeNode(
注释代码删除

2022-04-25 11:22 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/argsort.cc
> +void ArgsortMapper::Opset10() {
这里为什么是Opset10，而不是Opset11呢？

2022-04-25 11:22 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/argsort.cc
> +         "While input shape is dynamic, it only support opset version>=10.");
为什么这个判断不在GetMinOpset里面

2022-04-25 11:22 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/dist.cc
> +  if (fabs(p_) < 1e-6) {
到底小于1e-06时，有没有要求是opset9，看在这里又给了实现

2022-04-26 06:08 UTC, neonhuang commented on paddle2onnx/mapper/tensor/argsort.cc
> +  auto out_node = helper_->MakeNode(
done

2022-04-26 08:16 UTC, neonhuang commented on paddle2onnx/mapper/tensor/argsort.cc
> +        << "While descending=False only support opset version>=11., "
done

2022-04-26 08:50 UTC, neonhuang commented on paddle2onnx/mapper/tensor/argsort.cc
> +void ArgsortMapper::Opset10() {
因为top还有10的类型

2022-04-26 08:50 UTC, neonhuang commented on paddle2onnx/mapper/tensor/argsort.cc
> +         "While input shape is dynamic, it only support opset version>=10.");
done

2022-04-26 08:58 UTC, neonhuang commented on paddle2onnx/mapper/tensor/dist.cc
> +  if (fabs(p_) < 1e-6) {
done

2022-04-26 11:07 UTC, jiangjiajun approved these changes

2022-05-04 03:59 UTC, merged