add expand c++ op
PaddlePaddle/Paddle2ONNX pull request #713
Opened 2022-04-22 07:26 UTC by neonhuang

add expand c++ op

2022-04-22 07:33 UTC, jiangjiajun commented
参照上个PR，添加测试

2022-04-24 11:41 UTC, jiangjiajun requested changes

2022-04-24 11:41 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/expand.h
> +  std::vector<int64_t> expand_times_;
代码缩进不对，提交代码前`sh commit-prepare.sh`

2022-04-24 11:41 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/expand_as.cc
> +  } else {
为什么有个空的else

2022-04-24 11:41 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/expand_as.cc
> +     "Not find attribute: 'target_shape' or tensor 'target_tensor'");
在新的代码中，设计的原则时，如果有不支持的情况，则在最开始GetMinOpset时，就发现，不会再继续转换下去。因此不允许在Opset函数中出现GetMinOpset未检查到的情况而中止

2022-04-24 11:41 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/expand_as.h
> +  int32_t GetMinOpset(bool verbose = false) { return 8;};
同前一个PR

2022-04-24 11:41 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/expand_v2.h
>    int32_t GetMinOpset(bool verbose = false) { return 8; }
这里先前没添加日志提示，也对应加一下`Logger(verbose, 8) << RequireOpset(8) << std::endl;`

2022-04-25 10:12 UTC, neonhuang commented on paddle2onnx/mapper/tensor/expand_v2.h
>    int32_t GetMinOpset(bool verbose = false) { return 8; }
done

2022-04-25 10:13 UTC, neonhuang commented on paddle2onnx/mapper/tensor/expand_as.h
> +  int32_t GetMinOpset(bool verbose = false) { return 8;};
done

2022-04-25 10:15 UTC, neonhuang commented on paddle2onnx/mapper/tensor/expand.h
> +  std::vector<int64_t> expand_times_;
done

2022-04-25 10:25 UTC, neonhuang commented on paddle2onnx/mapper/tensor/expand_as.cc
> +  } else {
done

2022-04-25 10:25 UTC, neonhuang commented on paddle2onnx/mapper/tensor/expand_as.cc
> +     "Not find attribute: 'target_shape' or tensor 'target_tensor'");
done

2022-04-26 03:10 UTC, jiangjiajun requested changes

2022-04-26 03:10 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/expand_as.cc
> +         "Not find attribute: 'target_shape' or tensor 'target_tensor'");
Paddle2ONNX的工作流程是这样。 在转换一个模型时，首先会遍历模型的每个OP，然后调用GetMinOpset来确认模型是否可转换，以及最小的OPset应该是怎样。

所以在GetMinOpset里面，如果调用了Assert，那就在检查阶段直接中止了

GetMinOpset中只用来确认OP是否可转，或者最小的OPset，如果不可转，就返回-1

2022-04-26 03:10 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/expand_as.cc
> +         "Not find attribute: 'target_shape' or tensor 'target_tensor'");
```
if (target_shape_.size() ==0 && !HasInput("target_tensor")) {
  Error() << "Attribute `target_shape` and input tensor `target_tensor` is not exist" << std::endl;
  return -1;
}
```

2022-04-26 03:16 UTC, neonhuang commented on paddle2onnx/mapper/tensor/expand_as.cc
> +         "Not find attribute: 'target_shape' or tensor 'target_tensor'");
done

2022-04-26 05:55 UTC, jiangjiajun approved these changes

2022-04-26 08:15 UTC, merged