quantize model support in CPP version
PaddlePaddle/Paddle2ONNX pull request #761
Opened 2022-06-01 13:00 UTC by yeliang2258

1. Add quantize op.
2. support other backend support.

2022-06-03 07:51 UTC, jiangjiajun requested changes

2022-06-03 07:51 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize/dequantize_linear.cc
> +    Logger(verbose, 13) << RequireOpset(13) << std::endl;
在输入最低Opset要求时，如果这个OP至少要求为X时，直接打出的信息就是RequireOpset(X)，但分为多种情况的时候，就再额外给出一些信息提示，如这里就是
```
Logger(verbose, 13) << "While size of scales greater than 1, " << RequireOpset(13) << std::endl;
```

2022-06-03 07:51 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize/dequantize_linear.cc
> +  for (auto i : scales) {
for (auto &i : scales)

2022-06-03 07:51 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize/dequantize_linear.cc
> +    Assert(quant_axis_ == 1,
如果存在这种Assert的情况，那么需要加到GetMinOpset里面。 

前面有部分OpsetX()函数中，会调用Assert进行判断，但这些Assert判断也同时会在GetMinOpset先调用一次

2022-06-03 07:51 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize/dequantize_linear.cc
> +    Assert(quant_axis_ == 1 || quant_axis_ == 0,
同上

2022-06-03 07:51 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize/dequantize_linear.cc
> +           "be 0 or 1.");
When the rank of input is 4, the attribute quant_axis requires to be 0 or 1.

2022-06-03 07:51 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize/dequantize_linear.cc
> +    }
这里这段对Weight进行处理的逻辑独立成一个函数出来调用

2022-06-03 07:51 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize/dequantize_linear.cc
> +  Weight save_weight;
原先的weigth是int8的吗，这里如果是指转换后的float weight，那变量名就命名成fp32_weight

2022-06-03 07:51 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize/quantize_linear.cc
> +    Logger(verbose, 13) << RequireOpset(13) << std::endl;
同上
Logger(verbose, 13) << "While size of scales greater than 1, " << RequireOpset(13) << std::endl;

2022-06-03 07:51 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.h
> +  void process_quantize_model(
函数驼峰命名风格统一

2022-06-03 07:51 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.h
> +struct QuantizeModelProcess {
这个命名改成QuantizeModelProcessor

2022-06-03 07:51 UTC, jiangjiajun commented on paddle2onnx/mapper/exporter.cc
> +  quantize_model_process.process_quantize_model(
默认即为onnxruntime类型，无需产出max_range文本

2022-06-03 07:51 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +    outfile.open("max_range.txt", std::ios::out);
代码中硬编码一个当前位置写入文件是非常不好的做法，因为有可能会导致程序挂掉，无法判断用户执行程序的目录是否可读。 在这里同时也需要加上文件是否成功打开的判断。

2022-06-03 07:51 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +    OnnxHelper& helper, const std::string deploy_backend) {
const std::string& 改为引用

2022-06-03 08:33 UTC, jiangjiajun commented
仍缺乏op的单测，以及模型的单测

2022-06-05 03:50 UTC, yeliang2258 commented on paddle2onnx/mapper/exporter.cc
> +  quantize_model_process.process_quantize_model(
这个PR里还没有onnxruntime类型，后期实现之后会默认为onnxruntime类型

2022-06-11 03:26 UTC, jiangjiajun requested changes
只改动提comment的几处代码，其余不要修改即可Merge

2022-06-11 03:26 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +      std::cout << "[WARNING] Can not open max_range.txt." << std::endl;
日志改成使用Warn() << "Failed to write range information in current location." << std::endl;

2022-06-11 07:05 UTC, yeliang2258 commented on paddle2onnx/mapper/quantize_helper.cc
> +      std::cout << "[WARNING] Can not open max_range.txt." << std::endl;
Warn() 是来自Mapper，而且要输出op_type等信息，这里我增强提示信息便可

2022-06-12 03:02 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +      std::cout << "[WARNING] Can not open max_range.txt." << std::endl;
那改成`P2OLogger() << "[WARNING] ....."`， 统一日志的输出方式

2022-06-12 14:04 UTC, merged