Add scatter operator support
PaddlePaddle/Paddle2ONNX pull request #767
Opened 2022-06-07 03:49 UTC by yeliang2258

1. Add scatter operator support

2022-06-09 08:39 UTC, jiangjiajun requested changes

2022-06-09 08:39 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/scatter.cc
> +  if (!overwrite_) {
overwrite_应该可以组合实现 https://github.com/apache/tvm/blob/main/python/tvm/relay/frontend/paddlepaddle.py#L1701

2022-06-09 08:39 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/scatter.cc
> +  return 11;
前面需加上 Logger(verbose, 11) << RequireOpset(11) << std::endl;

2022-06-09 08:39 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/scatter.cc
> +  auto input_ids_info = parser_->GetOpInput(block_idx_, op_idx_, "Ids");
同GatherND

2022-06-11 03:31 UTC, jiangjiajun requested changes

2022-06-11 03:31 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/scatter.cc
> +  if (!overwrite_) {
在非16版本采用组合实现， Paddle2ONNX现在没有支持16

2022-06-11 03:36 UTC, jiangjiajun requested changes

2022-06-11 03:36 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/scatter.cc
> +  if (!overwrite_) {
OP16的话，我们需要重新看下16这个版本对哪些OP进行了升级，需要在Paddle2ONNX里面全局更新下。 当前只在这里一个支持意义不大。 但是可以先把这几行代码列一个TODO
后面来统一更新

2022-06-12 05:23 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/scatter.cc
> +  if (!overwrite_) {
移除OP16，使用组合方式实现

2022-06-12 14:58 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/scatter.cc
> +  if (!overwrite_) {
Done 新增了TODO

2022-06-13 05:08 UTC, jiangjiajun requested changes

2022-06-13 05:08 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/scatter.cc
> +  if (!overwrite_) {
- 在现有的opset版本，即1~15，是否能够通过组合实现`!overwrite_`的情况
- Opset16完全注释掉，尽量不给用户暴露未测试的功能

2022-06-15 09:38 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/scatter.cc
> +  if (!overwrite_) {
增加TODO，支持opset vesion 16之后支持!overwrite_的情况

2022-06-15 12:04 UTC, jiangjiajun commented on tests/test_auto_scan_scatter.py
> +
为啥需要改单测

2022-06-15 12:10 UTC, yeliang2258 commented on tests/test_auto_scan_scatter.py
> +
现在比他之前测的全

2022-06-15 14:48 UTC, merged