Add one_hot_v2 operator support
PaddlePaddle/Paddle2ONNX pull request #768
Opened 2022-06-07 06:51 UTC by yeliang2258

1. Add one_hot_v2 operator support

2022-06-09 08:43 UTC, jiangjiajun requested changes

2022-06-09 08:43 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/one_hot_v2.cc
> +    Error() << "allow_out_of_range can not be true in one_hot_v2." << std::endl;
是cannot be true 还是is not supported

2022-06-09 08:43 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/one_hot_v2.cc
> +  return 9;
Logger(verbose, 9) << RequireOpset(9) << std::endl;

2022-06-09 08:43 UTC, jiangjiajun commented on paddle2onnx/mapper/tensor/one_hot_v2.cc
> +  auto output_info = parser_->GetOpOutput(block_idx_, op_idx_, "Out");
同GatherND

2022-06-09 09:39 UTC, yeliang2258 commented on paddle2onnx/mapper/tensor/one_hot_v2.cc
> +    Error() << "allow_out_of_range can not be true in one_hot_v2." << std::endl;
is not supported

2022-06-11 03:32 UTC, jiangjiajun approved these changes

2022-06-11 06:46 UTC, merged