Add ONNXRuntime backend support for quantize model
PaddlePaddle/Paddle2ONNX pull request #782
Opened 2022-06-15 03:37 UTC by yeliang2258

1. Add ONNXRuntime backend support for quantize model

2022-06-19 12:14 UTC, jiangjiajun requested changes

2022-06-19 12:14 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +#endif
这里不需要，就直接删除

2022-06-19 12:14 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +                                              const bool& update_io) {
update_io，看这个命名，像是更新输入输出。 在哪些情况下需要删除Node，却不需要更新输入输出

2022-06-19 12:14 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +#endif
以及上面RemoveIsolatedNodes函数都可以移除掉

2022-06-19 12:14 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +  }
else 如果需要Assert，就Assert掉

2022-06-19 12:14 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.h
> +  void AppendQuantizeTensor(const std::string& tensor,
添加注释， only_dequantize是用于什么的

2022-06-19 12:14 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.h
> +  std::vector<std::string> only_dequantize_tensors;
这两个变量加上注释

2022-06-19 12:14 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +  if (iter != name2node_dict_.end()) {
下面的循环赋值，改成更简洁
```
for (size_t i = 0; i < node->input_size(); ++i) {
  if (node->input(i) == old_name) {
    node->set_input(i, new_name);
  }
}
```

2022-06-19 12:14 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +    GetTopoSort();
这个函数改名为SortNodes()吧， GetXX函数一般会返回一个值

2022-06-19 12:14 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +        }
这里两行是不是也是`if (!CanBeQuantize(tensor_names))` ，如果是就统一成上面的写法吧

2022-06-19 12:14 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +  // 3. constant node in nodes
之所以要找3个途径，而不是1，或者1+2， 而是1+2+3，处理的是什么情况的问题

2022-06-19 12:14 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +            std::vector<int64_t> val(shape[0], 0);
这里是传入shape[0]，还是传入nums， 看上面写的像是nums，即这个Tensor的Numel

2022-06-19 12:14 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +  for (auto name : tensors_to_be_quantize) {
auto&

2022-06-19 12:14 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +                  << std::endl;
这个是应该Assert，还是WARNING即可。 进入这个条件判断是在预期中的吗？

2022-06-19 12:14 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +void QuantizeModelProcessor::RemoveIsolatedNodes() {
删除

2022-06-19 12:14 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +bool QuantizeModelProcessor::IsGraphOutput(const std::string name) {
string&

2022-06-19 12:14 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +    if (quant_axis == 1) {
改成
```
if (quant_axis == 0) {
} else if (quant_axis == 1) {
} else {
   Assert(false, "QuantizeModelProcessor::GetChannelWiseQuantizeInfo only supports quant_axis equals to 0 or 1, but now it's " + std::to_string(quant_axis) + ".");
}
```

2022-06-19 12:42 UTC, yeliang2258 commented on paddle2onnx/mapper/quantize_helper.cc
> +                                              const bool& update_io) {
更换node的时候

2022-06-19 12:51 UTC, yeliang2258 commented on paddle2onnx/mapper/quantize_helper.cc
> +        }
这个地方还有其他逻辑，所以这里不能合起来

2022-06-19 12:54 UTC, yeliang2258 commented on paddle2onnx/mapper/quantize_helper.cc
> +  // 3. constant node in nodes
查找权重时，需要先找更新过的权重，也就是在1中查找，如果找不到就在2中查找，3是为了在MergeConvAdd时在Constant node中找到Reshape OP的new shape信息

2022-06-19 13:04 UTC, yeliang2258 commented on paddle2onnx/mapper/quantize_helper.cc
> +            std::vector<int64_t> val(shape[0], 0);
更新了

2022-06-19 13:33 UTC, yeliang2258 commented on paddle2onnx/mapper/quantize_helper.cc
> +                  << std::endl;
改为Assert

2022-06-20 02:11 UTC, jiangjiajun requested changes

2022-06-20 02:11 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +               deploy_backend);
`Assert(false, [QuantizeModelProcessor] Only support 'onnxruntime' / 'others' as backend now, but now the backend is: " + deploy_backend + ".")`

其中Assert传入false才会终止，传入true，此行不会执行

2022-06-20 02:11 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +  // 3. constant node in nodes
所以是不是直接1 + 3即可， 2这个就没必要再找了

2022-06-20 05:12 UTC, jiangjiajun requested changes

2022-06-20 05:12 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +               deploy_backend);
英文注释一并改成上面写的

2022-06-20 08:17 UTC, yeliang2258 commented on paddle2onnx/mapper/quantize_helper.cc
> +               deploy_backend);
Done

2022-06-20 08:44 UTC, jiangjiajun requested changes

2022-06-20 08:44 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +  // 3. constant node in nodes
这里应该是只用1+3就行？

2022-06-20 08:45 UTC, yeliang2258 commented
不行，BN里面的参数在2里面

2022-06-20 08:47 UTC, jiangjiajun commented
哪种情况下会有参数在2而不是3里面，这个有点奇怪。 理认上Paddle的所有参数都在3里面

2022-06-20 08:48 UTC, yeliang2258 commented
3的参数是在node里面的，比如Reshape的第二个输入，是在转换OP的时候生成的constant node，保存在nodes里面，但是params里面没有

2022-06-20 08:50 UTC, jiangjiajun commented
> constant参数2和3里面都有，2的参数是paddle graph里面的权重参数等，3的constant node是在OP转换的时候生成的，比如Reshape的第二个输入，是在转换OP的时候生成的constant node，保存在3里面，但是2里面没有

那也就是2是3的子集吗？

2022-06-20 08:52 UTC, yeliang2258 commented
2和3就没有关系，2是paddle里面的权重，3是OP转换时生成的

2022-06-21 05:46 UTC, jiangjiajun requested changes

2022-06-21 05:46 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize/dequantize_linear.cc
> +  }
没有处理没有round_type的情况。

这里改成如下的形式
1. 在构造函数里面来获取round_type的值，如果能获取到，就是round_type真实的值。 否则就是-1或其它值（取决于PaddleSlim的PR是如何定义的）
2. 在GetMinOpset里面判断round_type的值，如果不为想要的值，就返回-1

2022-06-21 05:46 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize/dequantize_linear.h
> +  int64_t round_type_ = 0;  // 0: rounding to nearest ties to even. 1: rounding
现在这里默认写的是0，但根据群里的沟通，默认应该是Paddle2ONNX不支持的情况？

2022-06-21 05:46 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize/quantize_linear.cc
> +  }
同上

2022-06-21 05:46 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize/quantize_linear.h
> +                            // to nearest ties away from zero.
同上

2022-06-21 06:11 UTC, yeliang2258 commented on paddle2onnx/mapper/quantize/dequantize_linear.h
> +  int64_t round_type_ = 0;  // 0: rounding to nearest ties to even. 1: rounding
![image](https://user-images.githubusercontent.com/30516196/174728576-48fd086c-e343-4b54-8ecf-a4d93e2fc86f.png)

2022-06-21 06:12 UTC, yeliang2258 commented on paddle2onnx/mapper/quantize/dequantize_linear.h
> +  int64_t round_type_ = 0;  // 0: rounding to nearest ties to even. 1: rounding
PR里面quantize_linear写的默认是我们支持的情情况

2022-06-21 06:18 UTC, yeliang2258 commented on paddle2onnx/mapper/quantize/dequantize_linear.cc
> +  }
Done

2022-06-21 07:38 UTC, jiangjiajun approved these changes

2022-06-21 08:18 UTC, merged