Fix quantize OP Matmul and Relu
PaddlePaddle/Paddle2ONNX pull request #788
Opened 2022-06-24 10:05 UTC by yeliang2258

1. Add quantize info broadcast between the input and output of Identity OP.
2. Fix Matmul and Relu OP in quantize_helper
3. Fix quantize model test
4. Add some quantized model test
5. Fix the test of layer_norm

2022-06-27 02:29 UTC, jiangjiajun requested changes

2022-06-27 02:29 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +      Assert(max_val >= 0, "[GetChannelWiseQuantizeInfo] Get minus scale");
负数使用Negative

另外在抛出的提示中，写出更直观的提示，例如`[GetChannelWiseQuantizeInfo] Require the scale >= 0, but now it's " + std::to_string(max_value) + ".")`

2022-06-27 02:29 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +      Assert(max_val >= 0, "[GetChannelWiseQuantizeInfo] Get minus scale");
另外是出于什么原因需要在这里添加这个判断，我看上面已经取过abs操作了

2022-06-27 02:45 UTC, yeliang2258 commented on paddle2onnx/mapper/quantize_helper.cc
> +      Assert(max_val >= 0, "[GetChannelWiseQuantizeInfo] Get minus scale");
Done

2022-06-28 07:17 UTC, jiangjiajun approved these changes

2022-06-29 06:14 UTC, merged