Add quantize model related doc
PaddlePaddle/Paddle2ONNX pull request #801
Opened 2022-07-07 09:44 UTC by yeliang2258

1. Add quantize model related doc.
2. change abs to fabs

2022-07-07 13:10 UTC, jiangjiajun requested changes

2022-07-07 13:10 UTC, jiangjiajun commented on README.md
> +如需转换PaddleSlim的量化模型，量化模型时请开启onnx_format和is_full_quantize开关，转换时和非量化模型的导出方式一致，不用特殊配置。PaddleSlim量化demo和接口请查阅：[PaddleSlim离线量化demo](https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/quant/quant
ReadME中不写这么多，这里全部放到，在Readme中只需写明

PaddleSlim量化模型导出请参考[量化模型导出ONNX](docs/zh/quantize.md)

可以从用户的角度给出说明
1. 导出量化模型时提示`fake_quantize_dequantize_linear`不支持。。。。?
Paddle2ONNX目前仅支持PaddleSlim导出离线量化且为全量化的模型，用户在使用PaddleSlim进行量化导出时，需指定参数xxxxxx

参考如下示例

2022-07-08 02:57 UTC, yeliang2258 commented on README.md
> +如需转换PaddleSlim的量化模型，量化模型时请开启onnx_format和is_full_quantize开关，转换时和非量化模型的导出方式一致，不用特殊配置。PaddleSlim量化demo和接口请查阅：[PaddleSlim离线量化demo](https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/quant/quant
Done

2022-07-08 05:27 UTC, jiangjiajun approved these changes

2022-07-08 05:27 UTC, merged