Add Attention Fuse pass
PaddlePaddle/Paddle2ONNX pull request #809
Opened 2022-07-15 09:30 UTC by wjj19950828

添加Attention fuse pass，仅支持ORT

2022-07-16 06:36 UTC, jiangjiajun requested changes

2022-07-16 06:36 UTC, jiangjiajun commented on paddle2onnx/mapper/exporter.cc
> +MapperHelper *MapperHelper::helper = nullptr;
代码风格被重新格式化了，需要修改回去

2022-07-16 06:36 UTC, jiangjiajun commented on paddle2onnx/optimizer/fuse_attention.h
> +  bool patternMatchPredicate(Node *node) override {
在原始代码中都使用指针符号靠左对齐，新添加的代码需对齐

2022-07-16 06:36 UTC, jiangjiajun commented on paddle2onnx/optimizer/fuse_attention.h
> +
这里有一幅整图的fuse前后对比

在下面的代码中也对应写出fuse中每一步的几个点节（而不单纯只用QKV WEIGHT来描述）

2022-07-16 06:36 UTC, jiangjiajun commented on paddle2onnx/optimizer/paddle2onnx_optimizer.h
> +    passes.push_back("fuse_attention");
这不是一个必选的fuse，所以需要额外的开关来控制

2022-07-16 06:36 UTC, jiangjiajun commented
这个PR，需给出最终的实验数据和效果

2022-07-18 17:31 UTC, wjj19950828 commented on paddle2onnx/mapper/exporter.cc
> +MapperHelper *MapperHelper::helper = nullptr;
Done.

2022-07-18 17:36 UTC, wjj19950828 commented on paddle2onnx/optimizer/fuse_attention.h
> +  bool patternMatchPredicate(Node *node) override {
Done.

2022-07-18 17:36 UTC, wjj19950828 commented on paddle2onnx/optimizer/fuse_attention.h
> +
Done.添加相关注释

2022-07-18 17:37 UTC, wjj19950828 commented on paddle2onnx/optimizer/paddle2onnx_optimizer.h
> +    passes.push_back("fuse_attention");
Done.添加```enable_extra_ort_opt```开关，默认为False

2022-07-18 17:39 UTC, wjj19950828 commented
> 这个PR，需给出最终的实验数据和效果

在描述中给出相关实验数据，CPU上增加repeat次数，解决方差较大问题

2024-05-22 03:45 UTC, closed without merging