Add deploy backend option support
PaddlePaddle/Paddle2ONNX pull request #819
Opened 2022-07-25 12:21 UTC by yeliang2258

Added deploy backend option support

2022-07-26 03:59 UTC, jiangjiajun requested changes

2022-07-26 03:59 UTC, jiangjiajun commented on paddle2onnx/__init__.py
> +           deploy_backend="onnxruntime",
默认参数默认规则往后面追加，避免影响现有调用代码

2022-07-26 03:59 UTC, jiangjiajun commented on paddle2onnx/converter.cc
> +    std::string deploy_backend, CustomOp* ops, int op_count) {
string，改为const std::string&， 同时参数默认往后追加，不要往中间塞，避免影响已经依赖paddle2onnx的代码

2022-07-26 07:11 UTC, jiangjiajun requested changes

2022-07-26 07:11 UTC, jiangjiajun commented on paddle2onnx/converter.h
> +#include <string>
由于gcc版本问题，不在头文件中不引入string， string改为char*

2022-07-26 07:11 UTC, jiangjiajun commented on paddle2onnx/converter.h
同上

2022-07-26 07:11 UTC, jiangjiajun commented on paddle2onnx/converter.h
> +#include <string>
除converter.h之外，其余地方可使用string

2022-07-26 07:11 UTC, jiangjiajun commented on paddle2onnx/cpp2py_export.cc
> -
这段代码为啥要删除

2022-07-26 07:19 UTC, yeliang2258 commented on paddle2onnx/cpp2py_export.cc
> -
这个代码多余了吧，下面的代码包括了这里面的情况，要不你测试一下？

2022-07-26 07:49 UTC, jiangjiajun commented on paddle2onnx/cpp2py_export.cc
> -
这里添加这段代码逻辑，是为了避免创建size为0的数组。 我没有测过多平台情况，但根据搜到的博文提到，这个在gcc编译器中，为0的数组是合法的，但在其它编译器中，可能会出错

2022-07-26 09:45 UTC, yeliang2258 commented on paddle2onnx/cpp2py_export.cc
> -
Done

2022-07-27 05:53 UTC, jiangjiajun approved these changes

2022-07-27 06:03 UTC, merged