Fix quantize model for TRT backend
PaddlePaddle/Paddle2ONNX pull request #830
Opened 2022-07-28 07:07 UTC by yeliang2258

1. According to TRT's quantization tool, each quantized conv should have its own QDQ
2. Add scale value check，scales of QDQ must be positive

2022-07-28 11:46 UTC, jiangjiajun requested changes

2022-07-28 11:46 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize/dequantize_linear.cc
> +    if (i <= 1e-10) all_positive = false;
风格统一改成if后的语句用花括号括起来。
也可以改成 all_positive = all_positive && (i > 1e-10);

2022-07-28 11:46 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize/dequantize_linear.cc
> +    if (i <= 1e-10) all_positive = false;
另外这种处理不会导致结果有问题吗

2022-07-28 11:46 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize/quantize_linear.cc
> +    if (i <= 1e-10) all_positive = false;
同上，另外auto i也改为auto& i吧

2022-07-28 12:24 UTC, yeliang2258 commented on paddle2onnx/mapper/quantize/dequantize_linear.cc
> +    if (i <= 1e-10) all_positive = false;
修改了，TRT的时候才加这个逻辑，因为TRT如果有scale为0就会报错

2022-07-29 06:16 UTC, jiangjiajun commented
新的代码我看又改了处理逻辑，现在只输出提示，不再处理scale了吗

2022-07-29 06:28 UTC, yeliang2258 commented
> 新的代码我看又改了处理逻辑，现在只输出提示，不再处理scale了吗

在quantize_helper中处理，backend为TRT的时候丢弃掉这个scale信息，因为TRT会报错，ORT的时候没有要求，就不需要处理了

2022-07-29 06:31 UTC, jiangjiajun approved these changes

2022-07-29 06:31 UTC, merged