Replace Explicit Quantization to Implicit Quantization for TensorRT backend
PaddlePaddle/Paddle2ONNX pull request #856
Opened 2022-08-16 03:55 UTC by yeliang2258

Replace Explicit Quantization to Implicit Quantization for TensorRT backend

2022-08-19 09:05 UTC, jiangjiajun requested changes

2022-08-19 09:05 UTC, jiangjiajun commented on docs/zh/quantize.md
> +(1) 检查机器是否支持 avx512_vnni 指令，在支持 avx512_vnni 的 CPU 上精度和加速效果最好
avx2, 512, vnni？

2022-08-19 09:05 UTC, jiangjiajun commented on paddle2onnx/mapper/exporter.h
> +                  const std::string& scale_file = "calibration_table.txt");
这里默认值设为空，当在转换量化模型时，如若scale_file为空，给出提示，而不是直接提示打不开calibration_table.txt
```
The PaddlePaddle model is a quantized model, it requires a scale_file e.g calibration_table.txt while exporting to ONNX, please refer to https://github.com/PaddlePaddle/Paddle2ONNX/quantize.md.
```

2022-08-19 09:05 UTC, jiangjiajun commented on paddle2onnx/command.py
> +        default="calibration_table.txt",
默认值设为空，参考下面的comment

2022-08-19 09:05 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +  // read out_scale.txt for all the tensors
独立成一个子函数。 当前这个函数的代码已经过长，一般而言，一个函数的实现不要超过一页屏幕

2022-08-19 09:05 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +  cache_file.open("calibration.cache", std::ios::out);
代码中不使用hardcode的路径，另外这个文件的用处是什么？看了下上面的文档没有说明

2022-08-19 09:05 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +  cache_file << "TRT-8XXX-EntropyCalibration2" << std::endl;
写了这句话的意思是这个只能用在TensorRT8上面吗，如果有这种限制，文档需说明

2022-08-19 09:53 UTC, yeliang2258 commented on paddle2onnx/mapper/exporter.h
> +                  const std::string& scale_file = "calibration_table.txt");
paddleslim导出的表就叫calibration_table.txt，没有提供接口给我用户修改名字，而且导出的时候我会提示从哪里读取scale信息

2022-08-19 09:54 UTC, yeliang2258 commented on paddle2onnx/mapper/quantize_helper.cc
> +  cache_file.open("calibration.cache", std::ios::out);
这个就是TensorRT读取的cache文件

2022-08-19 09:55 UTC, yeliang2258 commented on paddle2onnx/mapper/quantize_helper.cc
> +  cache_file << "TRT-8XXX-EntropyCalibration2" << std::endl;
没有测试过TensorRT 7的版本

2022-08-19 10:10 UTC, jiangjiajun requested changes

2022-08-19 10:10 UTC, jiangjiajun commented on paddle2onnx/mapper/exporter.h
> +                  const std::string& scale_file = "calibration_table.txt");
无需关注paddleslim导出的文件名，这里让用户自行传入量化表路径，并在用户没传输时，给出友好的提示

例如用户导出的模型在slim_model路径下，则这里的使用方式是
```
paddle2onnx --model_dir slim_model --model_filename model.pdmodel --params_filename model.pdiparams --scale_file=slim_model/calibration_table.txt --save_file model.onnx
```

2022-08-19 10:10 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +  cache_file.open("calibration.cache", std::ios::out);
导出在设定的onnx模型同级目录下， 如`--save_file=new_model/model.onnx`，则保存在new_model下。 同时导出时，给出提示，
`The calibration information is saved in new_model/calibration.cache, refer doc https://github.com/PaddlePaddle/Paddle2ONNX/quantize.md#TensorRT8 for usage.`

2022-08-19 16:23 UTC, yeliang2258 commented on paddle2onnx/mapper/exporter.h
> +                  const std::string& scale_file = "calibration_table.txt");
calibration_table.txt和model文件是放在一起的，只需要指定名称就可以了，另外新增了cache filename的选项

2022-08-20 06:18 UTC, jiangjiajun requested changes

2022-08-20 06:18 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +                   "https://github.com/PaddlePaddle/Paddle2ONNX/quantize.md. "
这个链接打不开

2022-08-20 06:18 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +  if (!out_scale_file) {
前面说到把这个的默认值设成空的情况下，才判断给这个提示, 所以需要将`scale_file`的默认值设置为`""`。

1. 当值为空时，即`scale_file == ""`，是调用接口时，忘传参scale_file，因此给出这里这个提示

2. 当`!out_scale_file`时，是调用接口时，传的参scale_file无法正常打开，如不存在这个路径，或用户传错了路径，给出正常提示即可，如`Cannot read scale file: " << scale_file << ", please check if the file exist." << std::endl;`

2022-08-20 06:18 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +  cache_file << "TRT-XXXX-EntropyCalibration2" << std::endl;
看到删除了先前8这个数字，这样是可以适配更多版本TensorRT吗，是否有测试过。如果只能适配8，需要在quantize.md中给出明确的说明

2022-08-20 07:17 UTC, yeliang2258 commented on paddle2onnx/mapper/quantize_helper.cc
> +  cache_file << "TRT-XXXX-EntropyCalibration2" << std::endl;
Done

2022-08-20 07:36 UTC, yeliang2258 commented on paddle2onnx/mapper/quantize_helper.cc
> +  if (!out_scale_file) {
Done

2022-08-20 08:28 UTC, jiangjiajun requested changes

2022-08-20 08:28 UTC, jiangjiajun commented on paddle2onnx/mapper/quantize_helper.cc
> +         "for more information");
改成

```
Assert(scale_file != "", ....)
```
使用默认值来判断。提示中不出现提示`--scale_filename`这种，因为库的设计除了Python使用外，也会集成到Paddle框架和FastDeploy。

2022-08-20 08:28 UTC, jiangjiajun commented on paddle2onnx/command.py
> +        calibration_file = args.calibration_filename
鉴于在上面参数中filename，仅表示name，而非路径

这里的calibration_file 应该改成是 onnx_save_dir + calibration_file_name

2022-08-20 08:28 UTC, jiangjiajun commented on tests/onnxbase.py
> +                        True, {}, "onnxruntime", "calibration_table.txt",
这里的scale_file是否应该是 os.path.join(self.name, "calibration_table.txt")

2022-08-20 14:59 UTC, yeliang2258 commented on paddle2onnx/mapper/quantize_helper.cc
> +         "for more information");
Done

2022-08-20 15:01 UTC, yeliang2258 commented on paddle2onnx/command.py
> +        calibration_file = args.calibration_filename
Done

2022-08-20 15:02 UTC, yeliang2258 commented on tests/onnxbase.py
> +                        True, {}, "onnxruntime", "calibration_table.txt",
Done

2022-08-21 07:56 UTC, merged