External data support when model is bigger than 2G
PaddlePaddle/Paddle2ONNX pull request #942
Opened 2022-10-31 12:42 UTC by yeliang2258

External data support when model is bigger than 2G

2022-11-07 12:02 UTC, jiangjiajun requested changes

2022-11-07 12:02 UTC, jiangjiajun commented on paddle2onnx/command.py
> +        deploy_backend, calibration_file, external_file)
已经支持自动判断是否保存external_data，可以在Python API采用自动的方式，如果external_filename是None，则默认改为是args.model_filename 所在的同级目录下的model.bin

2022-11-07 12:02 UTC, jiangjiajun commented on paddle2onnx/mapper/exporter.cc
> +  std::fstream f(external_file_path, std::ios::out);
判断文件是否能打开

2022-11-07 14:14 UTC, yeliang2258 commented on paddle2onnx/command.py
> +        deploy_backend, calibration_file, external_file)
Done

2022-11-08 02:26 UTC, jiangjiajun requested changes

2022-11-08 02:26 UTC, jiangjiajun commented on paddle2onnx/command.py
> +            os.mkdir(base_path)
这个这个目录本身已经存在，这行代码是否会出错

2022-11-08 03:12 UTC, jiangjiajun approved these changes

2022-11-08 06:28 UTC, merged